// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Diffs from "./Diffs.res.mjs";
import * as State from "./State.res.mjs";
import * as Trees from "./Trees.res.mjs";
import * as Jotai from "jotai";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as Diffs$1 from "@pierre/diffs";
import * as InlineComment from "./InlineComment.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/diffs/react";
import * as React$2 from "@pierre/trees/react";

function str(prim) {
  return prim;
}

function header(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n    padding: 12px;\n    background-color: ",
              ";\n    border-bottom: 1px solid ",
              ";\n    transition: all 0.2s ease;\n  "
            ], [
              colors.surfaceBg,
              colors.border
            ]);
}

function button(colors) {
  return Html.css([
              "\n    padding: 6px 12px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    cursor: pointer;\n    transition: all 0.2s ease;\n\n    &:hover {\n      background-color: ",
              ";\n    }\n\n    &:active {\n      transform: translateY(1px);\n    }\n  "
            ], [
              colors.border,
              colors.buttonBg,
              colors.buttonFg,
              colors.hoverBg
            ]);
}

function askPiButton(colors, disabled) {
  return Html.css([
              "\n    padding: 6px 12px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    cursor: ",
              ";\n    opacity: ",
              ";\n    transition: all 0.2s ease;\n\n    &:hover {\n      background-color: ",
              ";\n    }\n\n    &:active {\n      transform: translateY(1px);\n    }\n  "
            ], [
              disabled ? colors.border : colors.focusBorder,
              disabled ? colors.buttonBg : colors.selectionBg,
              colors.buttonFg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.6" : "1",
              disabled ? colors.buttonBg : colors.hoverBg
            ]);
}

var container = Html.css(["display: flex; flex-direction: column; height: 100vh;"], []);

var content = Html.css(["\n    display: flex;\n    flex-direction: row;\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n  "], []);

function sidebar(colors) {
  return Html.css([
              "\n    width: 280px;\n    min-width: 220px;\n    max-width: 360px;\n    display: flex;\n    flex-direction: column;\n    min-height: 0;\n    border-right: 1px solid ",
              ";\n    background-color: ",
              ";\n    overflow: hidden;\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

var main = Html.css(["\n    flex: 1;\n    min-width: 0;\n    overflow: hidden;\n  "], []);

var diffWrapper = Html.css(["\n    scroll-margin-top: 8px;\n  "], []);

function treeHeader(colors) {
  return Html.css([
              "\n    padding: 10px 12px;\n    border-bottom: 1px solid ",
              ";\n    color: ",
              ";\n    font-family: monospace;\n    font-size: 12px;\n    font-weight: 600;\n    letter-spacing: 0.04em;\n    text-transform: uppercase;\n  "
            ], [
              colors.border,
              colors.fg
            ]);
}

function treeStyle(colors) {
  return {
          height: "100%",
          "--trees-fg-override": colors.fg,
          "--trees-bg-override": colors.surfaceBg,
          "--trees-border-color-override": colors.border,
          "--trees-selected-bg-override": colors.selectionBg,
          "--trees-selected-fg-override": colors.fg
        };
}

var loadingContainer = Html.css(["\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex: 1;\n    font-family: monospace;\n    font-size: 14px;\n  "], []);

function errorContainer(colors) {
  return Html.css([
              "\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n    gap: 12px;\n    flex: 1;\n    font-family: monospace;\n    color: ",
              ";\n    padding: 24px;\n  "
            ], [colors.dangerBg]);
}

var errorMessage = Html.css(["\n    text-align: center;\n    max-width: 400px;\n    white-space: pre-wrap;\n  "], []);

var Styles = {
  header: header,
  button: button,
  askPiButton: askPiButton,
  container: container,
  content: content,
  sidebar: sidebar,
  main: main,
  diffWrapper: diffWrapper,
  treeHeader: treeHeader,
  treeStyle: treeStyle,
  loadingContainer: loadingContainer,
  errorContainer: errorContainer,
  errorMessage: errorMessage
};

function App(props) {
  var match = Jotai.useAtom(State.isDarkAtom);
  var setIsDark = match[1];
  var isDark = match[0];
  var match$1 = Jotai.useAtom(State.themeColorsAtom);
  var loadedThemes = match$1[0];
  var match$2 = Jotai.useAtom(State.commentsAtom);
  var setComments = match$2[1];
  var comments = match$2[0];
  var currentColors = loadedThemes !== undefined ? (
      isDark ? loadedThemes.dark : loadedThemes.light
    ) : (
      isDark ? State.defaultUiColors : State.lightDefaultUiColors
    );
  var match$3 = React.useState(function () {
        return false;
      });
  var setIsAskingPi = match$3[1];
  var isAskingPi = match$3[0];
  var match$4 = React.useState(function () {
        return "PatchLoading";
      });
  var setPatchState = match$4[1];
  var patchState = match$4[0];
  React.useEffect((function () {
          var onSuccess = function (rawPatch) {
            var patches = Diffs$1.parsePatchFiles(rawPatch);
            setPatchState(function (param) {
                  return {
                          TAG: "PatchReady",
                          _0: patches
                        };
                });
            return Promise.resolve();
          };
          var onError = function (err) {
            var msg = (String(err).replace(/^Error: /, ''));
            setPatchState(function (param) {
                  return {
                          TAG: "PatchError",
                          _0: msg
                        };
                });
            return Promise.resolve();
          };
          Js_promise2.$$catch(Js_promise2.then(Ipc.callGetPatch(), onSuccess), onError);
        }), []);
  var headerStyle = header(currentColors);
  var buttonStyle = button(currentColors);
  var virtualizerWrapperRef = React.useRef(null);
  var savedScrollTop = React.useRef(0.0);
  var isInitialRender = React.useRef(true);
  var captureScrollTop = function () {
    var wrapper = virtualizerWrapperRef.current;
    if (wrapper == null) {
      return ;
    }
    var firstChild = wrapper.firstElementChild;
    if (!(firstChild == null)) {
      savedScrollTop.current = firstChild.scrollTop;
      return ;
    }
    
  };
  var diffFilePaths = React.useMemo((function () {
          if (typeof patchState !== "object") {
            return [];
          } else if (patchState.TAG === "PatchReady") {
            return patchState._0.flatMap(function (patch) {
                        return patch.files.map(function (fileDiff) {
                                    return Diffs.fileDiffName(fileDiff);
                                  });
                      });
          } else {
            return [];
          }
        }), [patchState]);
  var fileTree = React$2.useFileTree({
        initialExpansion: "open",
        paths: diffFilePaths,
        onSelectionChange: (function (selectedPaths) {
            var fileName = Belt_Array.get(selectedPaths, 0);
            if (fileName !== undefined) {
              var wrapper = virtualizerWrapperRef.current;
              if (wrapper == null) {
                return ;
              }
              var firstChild = wrapper.firstElementChild;
              if (!(firstChild == null)) {
                return ((function(scroller, fileName) {
            var el = document.getElementById(fileName);
            if (el != null && scroller.contains(el)) {
              var top = el.getBoundingClientRect().top - scroller.getBoundingClientRect().top + scroller.scrollTop;
              scroller.scrollTo({top: Math.max(0, Math.floor(top)), behavior: "instant"});
            }
          }))(firstChild, fileName);
              } else {
                return ;
              }
            }
            
          })
      });
  React.useEffect((function () {
          Trees.resetPaths(fileTree.model, diffFilePaths);
        }), [diffFilePaths]);
  var handleThemeToggle = function (_event) {
    captureScrollTop();
    setIsDark(function (prev) {
          return !prev;
        });
  };
  var handleAskPi = function (_event) {
    if (isAskingPi) {
      return ;
    }
    var payloadComments = Core__Array.filterMap(Object.keys(comments), (function (key) {
            var c = Js_dict.get(comments, key);
            if (c !== undefined && c.text.trim().length > 0 && c.aiReply === "AiIdle") {
              return {
                      commentKey: key,
                      text: c.text
                    };
            }
            
          }));
    if (payloadComments.length === 0) {
      return setComments(function (prev) {
                  var newDict = InlineComment.copyDict(prev);
                  Object.keys(newDict).forEach(function (key) {
                        var c = Js_dict.get(newDict, key);
                        if (c !== undefined && c.text.trim().length > 0 && c.aiReply === "AiIdle") {
                          newDict[key] = {
                            text: c.text,
                            aiReply: {
                              TAG: "AiDone",
                              _0: "No new questions — your comments are already reviewed."
                            }
                          };
                          return ;
                        }
                        
                      });
                  return newDict;
                });
    }
    setComments(function (prev) {
          var newDict = InlineComment.copyDict(prev);
          payloadComments.forEach(function (pc) {
                var c = Js_dict.get(newDict, pc.commentKey);
                if (c !== undefined) {
                  newDict[pc.commentKey] = {
                    text: c.text,
                    aiReply: {
                      TAG: "AiStreaming",
                      _0: ""
                    }
                  };
                  return ;
                }
                
              });
          return newDict;
        });
    setIsAskingPi(function (param) {
          return true;
        });
    var onSuccess = function (replies) {
      setComments(function (prev) {
            var newDict = InlineComment.copyDict(prev);
            replies.forEach(function (reply) {
                  var key = InlineComment.normalizeModelKey(reply.commentKey);
                  var c = Js_dict.get(newDict, key);
                  if (c !== undefined) {
                    newDict[key] = {
                      text: c.text,
                      aiReply: {
                        TAG: "AiDone",
                        _0: reply.reply
                      }
                    };
                    return ;
                  }
                  
                });
            return newDict;
          });
      setIsAskingPi(function (param) {
            return false;
          });
      return Promise.resolve();
    };
    var onError = function (_err) {
      var msg = (String(_err).replace(/^Error: /, ''));
      setComments(function (prev) {
            var newDict = InlineComment.copyDict(prev);
            payloadComments.forEach(function (pc) {
                  var c = Js_dict.get(newDict, pc.commentKey);
                  if (c !== undefined) {
                    newDict[pc.commentKey] = {
                      text: c.text,
                      aiReply: {
                        TAG: "AiError",
                        _0: msg
                      }
                    };
                    return ;
                  }
                  
                });
            return newDict;
          });
      setIsAskingPi(function (param) {
            return false;
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callAskPi(payloadComments), onSuccess), onError);
  };
  React.useEffect((function () {
          if (isInitialRender.current) {
            isInitialRender.current = false;
            return ;
          }
          var savedTop = savedScrollTop.current;
          var handle = requestAnimationFrame(function () {
                var wrapper = virtualizerWrapperRef.current;
                if (wrapper == null) {
                  return ;
                }
                var firstChild = wrapper.firstElementChild;
                if (!(firstChild == null)) {
                  firstChild.scrollTo({
                        top: savedTop,
                        behavior: "instant"
                      });
                  return ;
                }
                
              });
          return (function () {
                    cancelAnimationFrame(handle);
                  });
        }), [isDark]);
  var diffChildren = React.useMemo((function () {
          if (typeof patchState !== "object") {
            return [];
          } else if (patchState.TAG === "PatchReady") {
            return patchState._0.flatMap(function (patch) {
                        return patch.files.map(function (fileDiff, _i) {
                                    var fileName = Diffs.fileDiffName(fileDiff);
                                    return JsxRuntime.jsx("div", {
                                                children: JsxRuntime.jsx(InlineComment.make, {
                                                      fileDiff: fileDiff,
                                                      theme: {
                                                        light: "rose-pine-dawn",
                                                        dark: "tokyo-night"
                                                      },
                                                      themeType: isDark ? "dark" : "light",
                                                      uiColors: currentColors
                                                    }),
                                                className: diffWrapper,
                                                id: fileName
                                              }, fileName);
                                  });
                      });
          } else {
            return [];
          }
        }), [
        patchState,
        isDark
      ]);
  if (typeof patchState !== "object") {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("button", {
                              children: isDark ? "Light Mode" : "Dark Mode",
                              className: buttonStyle,
                              type: "button",
                              onClick: handleThemeToggle
                            }),
                        className: headerStyle
                      }),
                  JsxRuntime.jsx("div", {
                        children: "Loading diff...",
                        className: loadingContainer
                      })
                ],
                className: container
              });
  } else if (patchState.TAG === "PatchReady") {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("button", {
                                children: isAskingPi ? "⠋ Asking Pi..." : "🤖 Ask Pi",
                                className: askPiButton(currentColors, isAskingPi),
                                disabled: isAskingPi,
                                type: "button",
                                onClick: handleAskPi
                              }),
                          JsxRuntime.jsx("button", {
                                children: isDark ? "Light Mode" : "Dark Mode",
                                className: buttonStyle,
                                type: "button",
                                onClick: handleThemeToggle
                              })
                        ],
                        className: headerStyle
                      }),
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("aside", {
                                children: JsxRuntime.jsx(React$2.FileTree, {
                                      model: fileTree.model,
                                      header: Caml_option.some(JsxRuntime.jsx("div", {
                                                children: "Changed files",
                                                className: treeHeader(currentColors)
                                              })),
                                      style: Caml_option.some(treeStyle(currentColors))
                                    }),
                                className: sidebar(currentColors)
                              }),
                          JsxRuntime.jsx("main", {
                                children: JsxRuntime.jsx(React$1.Virtualizer, {
                                      children: diffChildren,
                                      style: Caml_option.some({"height": "100%", "overflow-y": "auto"})
                                    }),
                                ref: Caml_option.some(virtualizerWrapperRef),
                                className: main
                              })
                        ],
                        className: content
                      })
                ],
                className: container
              });
  } else {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("button", {
                              children: isDark ? "Light Mode" : "Dark Mode",
                              className: buttonStyle,
                              type: "button",
                              onClick: handleThemeToggle
                            }),
                        className: headerStyle
                      }),
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("div", {
                              children: "Failed to load diff:\n\n" + patchState._0,
                              className: errorMessage
                            }),
                        className: errorContainer(currentColors)
                      })
                ],
                className: container
              });
  }
}

var styled = Html.styled;

var make = App;

export {
  styled ,
  str ,
  Styles ,
  make ,
}
/* container Not a pure module */
