// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Raw from "./Raw.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Diffs from "./Diffs.res.mjs";
import * as Shiki from "./Shiki.res.mjs";
import * as State from "./State.res.mjs";
import * as Trees from "./Trees.res.mjs";
import * as Jotai from "jotai";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Markdown from "./Markdown.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as CommitView from "./CommitView.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ProjectView from "./ProjectView.res.mjs";
import * as Diffs$1 from "@pierre/diffs";
import * as InlineComment from "./InlineComment.res.mjs";
import * as PiPreferences from "./PiPreferences.res.mjs";
import * as SpecCheckView from "./SpecCheckView.res.mjs";
import * as NewFeatureView from "./NewFeatureView.res.mjs";
import * as ThemePreferences from "./ThemePreferences.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/diffs/react";
import * as React$2 from "@pierre/trees/react";

function str(prim) {
  return prim;
}

var appFont = "\"Ioskeley Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

function header(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n    gap: 16px;\n    padding: 12px;\n    background-color: ",
              ";\n    border-bottom: 1px solid ",
              ";\n    transition: all 0.2s ease;\n  "
            ], [
              colors.surfaceBg,
              colors.border
            ]);
}

function tabs(colors) {
  return Html.css([
              "\n    display: inline-flex;\n    align-items: center;\n    flex-shrink: 0;\n    padding: 3px;\n    border: 1px solid ",
              ";\n    border-radius: 7px;\n    background-color: ",
              ";\n  "
            ], [
              colors.border,
              colors.inputBg
            ]);
}

function tab(colors) {
  return Html.css([
              "\n    padding: 6px 12px;\n    border: 1px solid transparent;\n    border-radius: 4px;\n    background-color: transparent;\n    color: ",
              ";\n    font-family: ",
              ";\n    font-weight: 500;\n    cursor: pointer;\n    transition: background-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease;\n\n    &:hover {\n      background-color: ",
              ";\n      color: ",
              ";\n    }\n\n    &[aria-selected=\"true\"] {\n      border-color: ",
              ";\n      background-color: ",
              ";\n      color: ",
              ";\n      font-weight: 600;\n      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.18);\n    }\n\n    &[aria-selected=\"true\"]:hover {\n      background-color: ",
              ";\n    }\n\n    &:focus-visible {\n      outline: 2px solid ",
              ";\n      outline-offset: 1px;\n    }\n  "
            ], [
              colors.descriptionFg,
              appFont,
              colors.hoverBg,
              colors.fg,
              colors.focusBorder,
              colors.selectionBg,
              colors.fg,
              colors.selectionBg,
              colors.focusBorder
            ]);
}

var headerActions = Html.css(["\n    display: flex;\n    align-items: center;\n    gap: 8px;\n    margin-left: auto;\n  "], []);

var aiMenu = Html.css(["\n    position: relative;\n    display: inline-flex;\n\n    &:hover > div,\n    &:focus-within > div {\n      display: flex;\n    }\n  "], []);

function aiMenuPanel(colors) {
  return Html.css([
              "\n    position: absolute;\n    z-index: 50;\n    top: 100%;\n    right: -20px;\n    display: none;\n    width: 220px;\n    flex-direction: column;\n    gap: 3px;\n    padding: 8px 20px 20px;\n\n    &::before {\n      content: \"\";\n      position: absolute;\n      z-index: -1;\n      inset: 5px 20px 15px;\n      border: 1px solid ",
              ";\n      border-radius: 7px;\n      background: ",
              ";\n      box-shadow: 0 12px 28px rgba(0, 0, 0, 0.28);\n    }\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

function aiMenuItem(colors, disabled) {
  return Html.css([
              "\n    width: 100%;\n    padding: 8px 10px;\n    border: 0;\n    border-radius: 4px;\n    background: transparent;\n    color: ",
              ";\n    text-align: left;\n    cursor: ",
              ";\n    opacity: ",
              ";\n\n    &:hover {\n      background: ",
              ";\n    }\n  "
            ], [
              colors.fg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.55" : "1",
              disabled ? "transparent" : colors.hoverBg
            ]);
}

function button(colors) {
  return Html.css([
              "\n    padding: 6px 12px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    cursor: pointer;\n    transition: all 0.2s ease;\n\n    &:hover {\n      background-color: ",
              ";\n    }\n\n    &:active {\n      transform: translateY(1px);\n    }\n  "
            ], [
              colors.border,
              colors.buttonBg,
              colors.buttonFg,
              colors.hoverBg
            ]);
}

function iconButton(colors) {
  return Html.css([
              "\n    width: 34px;\n    height: 32px;\n    display: inline-flex;\n    align-items: center;\n    justify-content: center;\n    padding: 0;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 1.385rem;\n    line-height: 1;\n    cursor: pointer;\n    transition: all 0.2s ease;\n\n    &:hover,\n    &[aria-pressed=\"true\"] {\n      background-color: ",
              ";\n      color: ",
              ";\n    }\n\n    &:focus-visible {\n      outline: 2px solid ",
              ";\n      outline-offset: 1px;\n    }\n  "
            ], [
              colors.border,
              colors.buttonBg,
              colors.buttonFg,
              colors.hoverBg,
              colors.fg,
              colors.focusBorder
            ]);
}

function askPiButton(colors, disabled) {
  return Html.css([
              "\n    padding: 6px 12px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    cursor: ",
              ";\n    opacity: ",
              ";\n    transition: all 0.2s ease;\n\n    &:hover {\n      background-color: ",
              ";\n    }\n\n    &:active {\n      transform: translateY(1px);\n    }\n  "
            ], [
              colors.focusBorder,
              colors.buttonBg,
              colors.buttonFg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.6" : "1",
              disabled ? colors.buttonBg : colors.buttonHoverBg
            ]);
}

var container = Html.css([
      "\n    display: flex;\n    flex-direction: column;\n    height: 100vh;\n    font-family: ",
      ";\n    font-size: 1rem;\n    line-height: 1.25;\n\n    & button,\n    & input,\n    & textarea,\n    & select {\n      font-family: inherit;\n      font-size: inherit;\n      line-height: inherit;\n    }\n  "
    ], [appFont]);

var content = Html.css(["\n    display: flex;\n    flex-direction: row;\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n  "], []);

function commitViewHost(hidden) {
  return Html.css([
              "\n    display: ",
              ";\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n  "
            ], [hidden ? "none" : "flex"]);
}

function sidebar(colors) {
  return Html.css([
              "\n    width: 280px;\n    min-width: 220px;\n    max-width: 360px;\n    display: flex;\n    flex-direction: column;\n    min-height: 0;\n    border-right: 1px solid ",
              ";\n    background-color: ",
              ";\n    overflow: hidden;\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

var main = Html.css(["\n    flex: 1;\n    min-width: 0;\n    overflow: hidden;\n  "], []);

var diffWrapper = Html.css(["\n    scroll-margin-top: 8px;\n  "], []);

function treeHeader(colors) {
  return Html.css([
              "\n    padding: 10px 12px;\n    border-bottom: 1px solid ",
              ";\n    color: ",
              ";\n    font-family: ",
              ";\n    font-size: 1rem;\n    font-weight: 600;\n  "
            ], [
              colors.border,
              colors.fg,
              appFont
            ]);
}

function treeStyle(colors) {
  return {
          height: "100%",
          "--trees-fg-override": colors.fg,
          "--trees-bg-override": colors.surfaceBg,
          "--trees-border-color-override": colors.border,
          "--trees-selected-bg-override": colors.selectionBg,
          "--trees-selected-fg-override": colors.fg,
          "--trees-font-family-override": appFont,
          "--trees-font-size-override": "1rem"
        };
}

var loadingContainer = Html.css([
      "\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex: 1;\n    font-family: ",
      ";\n    font-size: 1.077rem;\n  "
    ], [appFont]);

function errorContainer(colors) {
  return Html.css([
              "\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n    gap: 12px;\n    flex: 1;\n    font-family: ",
              ";\n    color: ",
              ";\n    padding: 24px;\n  "
            ], [
              appFont,
              colors.dangerBg
            ]);
}

var errorMessage = Html.css(["\n    text-align: center;\n    max-width: 400px;\n    white-space: pre-wrap;\n  "], []);

function reviewSummaryBar(colors) {
  return Html.css([
              "\n    padding: 8px 12px;\n    border-bottom: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-family: ",
              ";\n    font-size: 1rem;\n    line-height: 1.45;\n    white-space: pre-wrap;\n    max-height: 120px;\n    overflow: auto;\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.fg,
              appFont
            ]);
}

function reviewSummaryLabel(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-family: ",
              ";\n    font-size: 1rem;\n    font-weight: 600;\n    margin-right: 8px;\n  "
            ], [
              colors.descriptionFg,
              appFont
            ]);
}

function settingsPage(colors) {
  return Html.css([
              "\n    flex: 1;\n    overflow: auto;\n    padding: 32px;\n    background-color: ",
              ";\n    color: ",
              ";\n  "
            ], [
              colors.bg,
              colors.fg
            ]);
}

var settingsContent = Html.css(["\n    width: min(720px, 100%);\n    margin: 0 auto;\n  "], []);

var settingsTitle = Html.css(["\n    margin: 0 0 8px;\n    font-size: 1.846rem;\n  "], []);

function settingsDescription(colors) {
  return Html.css([
              "\n    margin: 0 0 24px;\n    color: ",
              ";\n    line-height: 1.5;\n  "
            ], [colors.descriptionFg]);
}

var settingsGrid = Html.css(["\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));\n    gap: 16px;\n  "], []);

function settingsCard(colors) {
  return Html.css([
              "\n    display: flex;\n    flex-direction: column;\n    gap: 10px;\n    padding: 18px;\n    border: 1px solid ",
              ";\n    border-radius: 8px;\n    background-color: ",
              ";\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

var settingsLabel = Html.css(["\n    font-size: 1.077rem;\n    font-weight: 700;\n  "], []);

function settingsSelect(colors) {
  return Html.css([
              "\n    width: 100%;\n    padding: 9px 10px;\n    border: 1px solid ",
              ";\n    border-radius: 5px;\n    background-color: ",
              ";\n    color: ",
              ";\n    cursor: pointer;\n\n    &:focus-visible {\n      outline: 2px solid ",
              ";\n      outline-offset: 1px;\n    }\n  "
            ], [
              colors.inputBorder,
              colors.inputBg,
              colors.inputFg,
              colors.focusBorder
            ]);
}

function settingsHint(colors) {
  return Html.css([
              "\n    min-height: 20px;\n    margin: 16px 0 0;\n    color: ",
              ";\n    font-size: 0.923rem;\n  "
            ], [colors.descriptionFg]);
}

var settingsSectionTitle = Html.css(["\n    margin: 28px 0 12px;\n    font-size: 1.23rem;\n  "], []);

function settingsCardHint(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 0.846rem;\n    line-height: 1.4;\n  "
            ], [colors.descriptionFg]);
}

function statusBar(colors) {
  return Html.css([
              "\n    min-height: 26px;\n    display: flex;\n    align-items: center;\n    justify-content: flex-end;\n    padding: 3px 10px;\n    border-top: 1px solid ",
              ";\n    background: ",
              ";\n    color: ",
              ";\n    font-size: 0.846rem;\n  "
            ], [
              colors.border,
              colors.surfaceBg,
              colors.descriptionFg
            ]);
}

var Styles = {
  appFont: appFont,
  header: header,
  tabs: tabs,
  tab: tab,
  headerActions: headerActions,
  aiMenu: aiMenu,
  aiMenuPanel: aiMenuPanel,
  aiMenuItem: aiMenuItem,
  button: button,
  iconButton: iconButton,
  askPiButton: askPiButton,
  container: container,
  content: content,
  commitViewHost: commitViewHost,
  sidebar: sidebar,
  main: main,
  diffWrapper: diffWrapper,
  treeHeader: treeHeader,
  treeStyle: treeStyle,
  loadingContainer: loadingContainer,
  errorContainer: errorContainer,
  errorMessage: errorMessage,
  reviewSummaryBar: reviewSummaryBar,
  reviewSummaryLabel: reviewSummaryLabel,
  settingsPage: settingsPage,
  settingsContent: settingsContent,
  settingsTitle: settingsTitle,
  settingsDescription: settingsDescription,
  settingsGrid: settingsGrid,
  settingsCard: settingsCard,
  settingsLabel: settingsLabel,
  settingsSelect: settingsSelect,
  settingsHint: settingsHint,
  settingsSectionTitle: settingsSectionTitle,
  settingsCardHint: settingsCardHint,
  statusBar: statusBar
};

function App(props) {
  var match = Jotai.useAtom(State.isDarkAtom);
  var setIsDark = match[1];
  var isDark = match[0];
  var match$1 = Jotai.useAtom(State.themeAtom);
  var setThemeNames = match$1[1];
  var themeNames = match$1[0];
  var match$2 = Jotai.useAtom(State.themeColorsAtom);
  var setLoadedThemes = match$2[1];
  var loadedThemes = match$2[0];
  var match$3 = Jotai.useAtom(State.commentsAtom);
  var setComments = match$3[1];
  var comments = match$3[0];
  var match$4 = Jotai.useAtom(State.reviewSuggestionsAtom);
  var setReviewSuggestions = match$4[1];
  var reviewSuggestions = match$4[0];
  var match$5 = Jotai.useAtom(State.piPreferencesAtom);
  var setPiPreferences = match$5[1];
  var piPreferences = match$5[0];
  var match$6 = Jotai.useAtom(State.piModelsAtom);
  var setPiModels = match$6[1];
  var piModels = match$6[0];
  var match$7 = Jotai.useAtom(State.piResolvedDefaultAtom);
  var setPiResolvedDefault = match$7[1];
  var piResolvedDefault = match$7[0];
  var match$8 = Jotai.useAtom(State.activePiRunAtom);
  var setActivePiRun = match$8[1];
  var activePiRun = match$8[0];
  var match$9 = Jotai.useAtom(State.featurePlanAtom);
  var currentColors = loadedThemes !== undefined ? (
      isDark ? loadedThemes.dark : loadedThemes.light
    ) : (
      isDark ? State.defaultUiColors : State.lightDefaultUiColors
    );
  var match$10 = React.useState(function () {
        return false;
      });
  var setIsAskingPi = match$10[1];
  var isAskingPi = match$10[0];
  var match$11 = React.useState(function () {

      });
  var setActiveReview = match$11[1];
  var activeReview = match$11[0];
  var match$12 = React.useState(function () {
        return "No full review has run yet.";
      });
  var setReviewSummary = match$12[1];
  var reviewSummary = match$12[0];
  var match$13 = React.useState(function () {
        return "Review";
      });
  var setReviewSummaryLabel = match$13[1];
  var match$14 = React.useState(function () {
        return "Review";
      });
  var setViewMode = match$14[1];
  var viewMode = match$14[0];
  var match$15 = React.useState(function () {
        return "";
      });
  var setRepoRoot = match$15[1];
  var match$16 = React.useState(function () {
        return false;
      });
  var setIsThemeLoading = match$16[1];
  var isThemeLoading = match$16[0];
  var match$17 = React.useState(function () {
        return false;
      });
  var setIsSpecCheckOpen = match$17[1];
  var match$18 = React.useState(function () {
        return "";
      });
  var setPiModelsError = match$18[1];
  var piModelsError = match$18[0];
  var themeLoadVersionRef = React.useRef(0);
  var lightThemeOptions = React.useMemo((function () {
          return ThemePreferences.getOptions("light");
        }), []);
  var darkThemeOptions = React.useMemo((function () {
          return ThemePreferences.getOptions("dark");
        }), []);
  React.useEffect((function () {
          var onSuccess = function (root) {
            setRepoRoot(function (param) {
                  return root;
                });
            return Promise.resolve();
          };
          var onError = function (_error) {
            return Promise.resolve();
          };
          Js_promise2.$$catch(Js_promise2.then(Ipc.callGetRepoRoot(), onSuccess), onError);
        }), []);
  var loadPiModels = function () {
    var onSuccess = function (result) {
      setPiModels(function (param) {
            return result.models;
          });
      setPiResolvedDefault(function (param) {
            return result.resolvedDefault;
          });
      setPiModelsError(function (param) {
            return "";
          });
      return Promise.resolve();
    };
    var onError = function (error) {
      setPiModelsError(function (param) {
            return Raw.errorMessage(error);
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callGetPiModels(), onSuccess), onError);
  };
  React.useEffect((function () {
          loadPiModels();
        }), []);
  React.useEffect((function () {
          PiPreferences.save(piPreferences);
        }), [piPreferences]);
  React.useEffect((function () {
          themeLoadVersionRef.current = themeLoadVersionRef.current + 1 | 0;
          var loadVersion = themeLoadVersionRef.current;
          ThemePreferences.save(themeNames);
          setIsThemeLoading(function (param) {
                return true;
              });
          var onMarkdownReady = function (param) {
            if (themeLoadVersionRef.current === loadVersion) {
              setIsThemeLoading(function (param) {
                    return false;
                  });
            }
            return Promise.resolve();
          };
          var onThemesReady = function (themes) {
            if (themeLoadVersionRef.current === loadVersion) {
              setLoadedThemes(function (param) {
                    return themes;
                  });
            }
            return Js_promise2.then(Markdown.preloadMarkdown(themeNames.light, themeNames.dark), onMarkdownReady);
          };
          var onThemeError = function (_error) {
            if (themeLoadVersionRef.current === loadVersion) {
              setIsThemeLoading(function (param) {
                    return false;
                  });
            }
            return Promise.resolve();
          };
          Js_promise2.$$catch(Js_promise2.then(Shiki.loadBothThemes(themeNames.light, themeNames.dark), onThemesReady), onThemeError);
        }), [themeNames]);
  var match$19 = React.useState(function () {
        return "PatchLoading";
      });
  var setPatchState = match$19[1];
  var patchState = match$19[0];
  var watcherReloadCountRef = React.useRef(__bakaDiffReloadRequestCount);
  var match$20 = React.useState(function () {
        return 0;
      });
  var setPatchReloadVersion = match$20[1];
  var patchReloadVersion = match$20[0];
  var requestPatchReload = function () {
    setPatchReloadVersion(function (prev) {
          return prev + 1 | 0;
        });
  };
  React.useEffect((function () {
          var interval = setInterval((function () {
                  var next = __bakaDiffReloadRequestCount;
                  if (next !== watcherReloadCountRef.current) {
                    watcherReloadCountRef.current = next;
                    return setPatchReloadVersion(function (prev) {
                                return prev + 1 | 0;
                              });
                  }

                }), 250);
          return (function () {
                    clearInterval(interval);
                  });
        }), []);
  React.useEffect((function () {
          console.log("[BAKA UI] fetching patch; reload version", patchReloadVersion);
          var onSuccess = function (rawPatch) {
            var patches = Diffs$1.parsePatchFiles(rawPatch);
            console.log("[BAKA UI] patch loaded bytes", rawPatch.length);
            console.log("[BAKA UI] parsed patch groups", patches.length);
            setPatchState(function (param) {
                  return {
                          TAG: "PatchReady",
                          _0: patches
                        };
                });
            return Promise.resolve();
          };
          var onError = function (err) {
            var msg = Raw.errorMessage(err);
            console.log("[BAKA UI] patch load error", msg);
            setPatchState(function (param) {
                  return {
                          TAG: "PatchError",
                          _0: msg
                        };
                });
            return Promise.resolve();
          };
          Js_promise2.$$catch(Js_promise2.then(Ipc.callGetPatch(), onSuccess), onError);
        }), [patchReloadVersion]);
  var headerStyle = header(currentColors);
  var buttonStyle = button(currentColors);
  var settingsAriaPressed = viewMode === "Settings" ? "true" : "false";
  var virtualizerWrapperRef = React.useRef(null);
  var savedScrollTop = React.useRef(0.0);
  var isInitialRender = React.useRef(true);
  var captureScrollTop = function () {
    var wrapper = virtualizerWrapperRef.current;
    if (wrapper == null) {
      return ;
    }
    var firstChild = wrapper.firstElementChild;
    if (!(firstChild == null)) {
      savedScrollTop.current = firstChild.scrollTop;
      return ;
    }

  };
  var diffFilePaths = React.useMemo((function () {
          if (typeof patchState !== "object") {
            return [];
          } else if (patchState.TAG === "PatchReady") {
            return patchState._0.flatMap(function (patch) {
                        return patch.files.map(function (fileDiff) {
                                    return Diffs.fileDiffName(fileDiff);
                                  });
                      });
          } else {
            return [];
          }
        }), [patchState]);
  var fileTree = React$2.useFileTree({
        initialExpansion: "open",
        paths: diffFilePaths,
        onSelectionChange: (function (selectedPaths) {
            var fileName = Belt_Array.get(selectedPaths, 0);
            if (fileName !== undefined) {
              var wrapper = virtualizerWrapperRef.current;
              if (wrapper == null) {
                return ;
              }
              var firstChild = wrapper.firstElementChild;
              if (!(firstChild == null)) {
                return ((function(scroller, fileName) {
            var el = document.getElementById(fileName);
            if (el != null && scroller.contains(el)) {
              var top = el.getBoundingClientRect().top - scroller.getBoundingClientRect().top + scroller.scrollTop;
              scroller.scrollTo({top: Math.max(0, Math.floor(top)), behavior: "instant"});
            }
          }))(firstChild, fileName);
              } else {
                return ;
              }
            }

          })
      });
  React.useEffect((function () {
          Trees.resetPaths(fileTree.model, diffFilePaths);
        }), [diffFilePaths]);
  var validReviewKeys = React.useMemo((function () {
          var keys = {};
          if (typeof patchState === "object" && patchState.TAG === "PatchReady") {
            patchState._0.forEach(function (patch) {
                  patch.files.forEach(function (fileDiff) {
                        var fileName = Diffs.fileDiffName(fileDiff);
                        Diffs.changedLineAnnotations(fileDiff).forEach(function (annotation) {
                              keys[InlineComment.makeKey(fileName, annotation.side, annotation.lineNumber)] = true;
                            });
                      });
                });
          }
          return keys;
        }), [patchState]);
  var handleThemeToggle = function (_event) {
    captureScrollTop();
    setIsDark(function (prev) {
          return !prev;
        });
  };
  var handleLightThemeChange = function ($$event) {
    var target = $$event.target;
    var themeName = target.value;
    captureScrollTop();
    setThemeNames(function (previous) {
          return {
                  light: themeName,
                  dark: previous.dark
                };
        });
  };
  var handleDarkThemeChange = function ($$event) {
    var target = $$event.target;
    var themeName = target.value;
    captureScrollTop();
    setThemeNames(function (previous) {
          return {
                  light: previous.light,
                  dark: themeName
                };
        });
  };
  var handleAskPi = function (_event) {
    if (isAskingPi) {
      return ;
    }
    console.log("[BAKA UI] Ask Pi button clicked");
    var payloadComments = Core__Array.filterMap(Object.keys(comments), (function (key) {
            var c = Js_dict.get(comments, key);
            if (c !== undefined && c.text.trim().length > 0 && c.aiReply === "AiIdle") {
              return {
                      commentKey: key,
                      text: c.text
                    };
            }

          }));
    if (payloadComments.length === 0) {
      console.log("[BAKA UI] Ask Pi has no pending comments");
      return setComments(function (prev) {
                  var newDict = InlineComment.copyDict(prev);
                  Object.keys(newDict).forEach(function (key) {
                        var c = Js_dict.get(newDict, key);
                        if (c !== undefined && c.text.trim().length > 0 && c.aiReply === "AiIdle") {
                          newDict[key] = {
                            text: c.text,
                            aiReply: {
                              TAG: "AiDone",
                              _0: "No new questions — your comments are already reviewed."
                            }
                          };
                          return ;
                        }

                      });
                  return newDict;
                });
    }
    var model = PiPreferences.resolve(piPreferences, piPreferences.inlineReviewModel);
    console.log("[BAKA UI] Ask Pi sending comment count", payloadComments.length);
    setComments(function (prev) {
          var newDict = InlineComment.copyDict(prev);
          payloadComments.forEach(function (pc) {
                var c = Js_dict.get(newDict, pc.commentKey);
                if (c !== undefined) {
                  newDict[pc.commentKey] = {
                    text: c.text,
                    aiReply: {
                      TAG: "AiStreaming",
                      _0: ""
                    }
                  };
                  return ;
                }

              });
          return newDict;
        });
    setIsAskingPi(function (param) {
          return true;
        });
    setActivePiRun(function (param) {
          return {
                  action: "Inline Q&A",
                  model: model
                };
        });
    var onSuccess = function (replies) {
      console.log("[BAKA UI] Ask Pi success replies", replies.length);
      setComments(function (prev) {
            var newDict = InlineComment.copyDict(prev);
            replies.forEach(function (reply) {
                  var key = InlineComment.normalizeModelKey(reply.commentKey);
                  console.log("[BAKA UI] Ask Pi applying reply key", key);
                  var c = Js_dict.get(newDict, key);
                  if (c !== undefined) {
                    newDict[key] = {
                      text: c.text,
                      aiReply: {
                        TAG: "AiDone",
                        _0: reply.reply
                      }
                    };
                    return ;
                  }

                });
            return newDict;
          });
      setIsAskingPi(function (param) {
            return false;
          });
      setActivePiRun(function (param) {

          });
      return Promise.resolve();
    };
    var onError = function (_err) {
      var msg = Raw.errorMessage(_err);
      console.log("[BAKA UI] Ask Pi error", msg);
      setComments(function (prev) {
            var newDict = InlineComment.copyDict(prev);
            payloadComments.forEach(function (pc) {
                  var c = Js_dict.get(newDict, pc.commentKey);
                  if (c !== undefined) {
                    newDict[pc.commentKey] = {
                      text: c.text,
                      aiReply: {
                        TAG: "AiError",
                        _0: msg
                      }
                    };
                    return ;
                  }

                });
            return newDict;
          });
      setIsAskingPi(function (param) {
            return false;
          });
      setActivePiRun(function (param) {

          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callAskPi(payloadComments, model), onSuccess), onError);
  };
  var handleFullReview = function (kind, _event) {
    if (activeReview !== undefined) {
      return ;
    }
    var match;
    match = kind === "CodeReview" ? [
        "Review",
        "Pi is reviewing the current diff...",
        "Pi review: "
      ] : [
        "Vulnerability Check",
        "Pi is checking the current diff for vulnerabilities...",
        "Pi vulnerability check: "
      ];
    var commentPrefix = match[2];
    var progress = match[1];
    var label = match[0];
    console.log("[BAKA UI] Full review button clicked", label);
    var tmp;
    tmp = kind === "CodeReview" ? piPreferences.codeReviewModel : piPreferences.securityReviewModel;
    var model = PiPreferences.resolve(piPreferences, tmp);
    setActiveReview(function (param) {
          return kind;
        });
    setActivePiRun(function (param) {
          return {
                  action: label,
                  model: model
                };
        });
    setReviewSummaryLabel(function (param) {
          return label;
        });
    setReviewSummary(function (param) {
          return progress;
        });
    var onSuccess = function (review) {
      console.log("[BAKA UI] Full review success summary", review.summary);
      console.log("[BAKA UI] Full review finding count", review.findings.length);
      setReviewSummary(function (param) {
            return review.summary;
          });
      setComments(function (prev) {
            var newDict = InlineComment.copyDict(prev);
            review.findings.forEach(function (finding) {
                  var key = InlineComment.normalizeModelKey(finding.commentKey);
                  var match = InlineComment.parseKey(key);
                  if (match !== undefined) {
                    var match$1 = Js_dict.get(validReviewKeys, key);
                    if (match$1 !== undefined && match$1) {
                      console.log("[BAKA UI] Full review inserting annotation", key);
                    } else {
                      console.log("[BAKA UI] Full review inserting file-level finding", key);
                    }
                    var text = commentPrefix + finding.summary;
                    var body = finding.body.trim().length > 0 ? finding.body : finding.summary;
                    newDict[key] = {
                      text: text,
                      aiReply: {
                        TAG: "AiDone",
                        _0: body
                      }
                    };
                    return ;
                  }
                  console.log("[BAKA UI] Full review skipping malformed finding", key);
                });
            return newDict;
          });
      setReviewSuggestions(function (prev) {
            var newDict = Raw.copyDict(prev);
            review.findings.forEach(function (finding) {
                  var key = InlineComment.normalizeModelKey(finding.commentKey);
                  var match = InlineComment.parseKey(key);
                  if (match !== undefined) {
                    console.log("[BAKA UI] Full review storing suggestion metadata", key);
                    newDict[key] = {
                      summary: finding.summary,
                      severity: finding.severity,
                      actionable: finding.actionable,
                      suggestion: finding.suggestion,
                      isApplying: false,
                      applyResult: undefined,
                      applyError: undefined
                    };
                    return ;
                  }

                });
            return newDict;
          });
      setActiveReview(function (param) {

          });
      setActivePiRun(function (param) {

          });
      return Promise.resolve();
    };
    var onError = function (err) {
      var msg = Raw.errorMessage(err);
      console.log("[BAKA UI] Full review error", msg);
      setReviewSummary(function (param) {
            return label + " failed: " + msg;
          });
      setActiveReview(function (param) {

          });
      setActivePiRun(function (param) {

          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callStartFullReview(kind, model), onSuccess), onError);
  };
  React.useEffect((function () {
          if (isInitialRender.current) {
            isInitialRender.current = false;
            return ;
          }
          var savedTop = savedScrollTop.current;
          var handle = requestAnimationFrame(function () {
                var wrapper = virtualizerWrapperRef.current;
                if (wrapper == null) {
                  return ;
                }
                var firstChild = wrapper.firstElementChild;
                if (!(firstChild == null)) {
                  firstChild.scrollTo({
                        top: savedTop,
                        behavior: "instant"
                      });
                  return ;
                }

              });
          return (function () {
                    cancelAnimationFrame(handle);
                  });
        }), [isDark]);
  var style_light = themeNames.light;
  var style_dark = themeNames.dark;
  var style = {
    light: style_light,
    dark: style_dark
  };
  var reviewCount = Object.keys(reviewSuggestions).length;
  var actionableReviewCount = Core__Array.reduce(Object.keys(reviewSuggestions), 0, (function (count, key) {
          var item = Js_dict.get(reviewSuggestions, key);
          if (item !== undefined && item.actionable) {
            return count + 1 | 0;
          } else {
            return count;
          }
        }));
  var reviewButtonTitle = reviewSummary + (
    reviewCount > 0 ? "\n\n" + reviewCount.toString() + " finding(s), " + actionableReviewCount.toString() + " actionable." : ""
  );
  var isReviewing = activeReview !== undefined;
  var isCodeReviewing = Caml_obj.equal(activeReview, "CodeReview");
  var isCheckingVulnerabilities = Caml_obj.equal(activeReview, "VulnerabilityCheck");
  var shouldShowReviewSummary = isReviewing || reviewSummary !== "No full review has run yet.";
  var reviewSummaryText = reviewSummary + (
    reviewCount > 0 ? "\n" + reviewCount.toString() + " finding(s), " + actionableReviewCount.toString() + " actionable." : ""
  );
  var diffChildren = React.useMemo((function () {
          if (typeof patchState !== "object") {
            return [];
          } else if (patchState.TAG === "PatchReady") {
            return patchState._0.flatMap(function (patch) {
                        return patch.files.map(function (fileDiff, _i) {
                                    var fileName = Diffs.fileDiffName(fileDiff);
                                    return JsxRuntime.jsx("div", {
                                                children: JsxRuntime.jsx(InlineComment.make, {
                                                      fileDiff: fileDiff,
                                                      theme: style,
                                                      themeType: isDark ? "dark" : "light",
                                                      uiColors: currentColors
                                                    }),
                                                className: diffWrapper,
                                                id: fileName
                                              }, fileName);
                                  });
                      });
          } else {
            return [];
          }
        }), [
        patchState,
        isDark,
        themeNames,
        currentColors
      ]);
  var renderModelSelect = function (label, hint, value, inherit, onChange) {
    return JsxRuntime.jsxs("label", {
                children: [
                  JsxRuntime.jsx("span", {
                        children: label,
                        className: settingsLabel
                      }),
                  JsxRuntime.jsx("span", {
                        children: hint,
                        className: settingsCardHint(currentColors)
                      }),
                  JsxRuntime.jsxs("select", {
                        children: [
                          inherit ? JsxRuntime.jsx("option", {
                                  children: "Use default" + (
                                    piPreferences.defaultModel !== "" ? " (" + piPreferences.defaultModel + ")" : (
                                        piResolvedDefault !== "" ? " (" + piResolvedDefault + ")" : ""
                                      )
                                  ),
                                  value: ""
                                }) : JsxRuntime.jsx("option", {
                                  children: "Pi default" + (
                                    piResolvedDefault !== "" ? " (" + piResolvedDefault + ")" : ""
                                  ),
                                  value: ""
                                }),
                          piModels.map(function (model) {
                                var id = model.provider + "/" + model.id;
                                return JsxRuntime.jsx("option", {
                                            children: model.provider + " / " + (
                                              model.name !== "" ? model.name : model.id
                                            ),
                                            value: id
                                          }, id);
                              })
                        ],
                        className: settingsSelect(currentColors),
                        value: value,
                        onChange: onChange
                      })
                ],
                className: settingsCard(currentColors)
              });
  };
  var renderSettings = function () {
    return JsxRuntime.jsx("main", {
                children: JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Settings",
                              className: settingsTitle
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Choose the Shiki themes used throughout BAKA. Your selections are saved automatically.",
                              className: settingsDescription(currentColors)
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "Light theme",
                                              className: settingsLabel
                                            }),
                                        JsxRuntime.jsx("select", {
                                              children: lightThemeOptions.map(function (theme) {
                                                    return JsxRuntime.jsx("option", {
                                                                children: theme.displayName,
                                                                value: theme.id
                                                              }, theme.id);
                                                  }),
                                              className: settingsSelect(currentColors),
                                              value: themeNames.light,
                                              onChange: handleLightThemeChange
                                            })
                                      ],
                                      className: settingsCard(currentColors)
                                    }),
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: "Dark theme",
                                              className: settingsLabel
                                            }),
                                        JsxRuntime.jsx("select", {
                                              children: darkThemeOptions.map(function (theme) {
                                                    return JsxRuntime.jsx("option", {
                                                                children: theme.displayName,
                                                                value: theme.id
                                                              }, theme.id);
                                                  }),
                                              className: settingsSelect(currentColors),
                                              value: themeNames.dark,
                                              onChange: handleDarkThemeChange
                                            })
                                      ],
                                      className: settingsCard(currentColors)
                                    })
                              ],
                              className: settingsGrid
                            }),
                        JsxRuntime.jsx("h2", {
                              children: "Pi models",
                              className: settingsSectionTitle
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Choose a default model, then override individual actions where a specialized or lower-cost model is more appropriate.",
                              className: settingsDescription(currentColors)
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                renderModelSelect("Default model", "Used by every action that does not have an explicit override.", piPreferences.defaultModel, false, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: $$event.target.value,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Inline Q&A", "Replies to comments in the diff and full-file viewer.", piPreferences.inlineReviewModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: $$event.target.value,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Code review", "General correctness and maintainability review.", piPreferences.codeReviewModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: $$event.target.value,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Security review", "Vulnerability-focused analysis.", piPreferences.securityReviewModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: $$event.target.value,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Specification check", "Compares the current changes against a supplied specification.", piPreferences.specReviewModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: $$event.target.value,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Suggestion implementation", "Generates patches for accepted review findings.", piPreferences.suggestionModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: $$event.target.value,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Suggestion validation", "Validates generated patches and creates a repair patch when needed.", piPreferences.validationModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: $$event.target.value,
                                                      planModel: previous.planModel,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Plan creation", "Inspects the repository and creates feature or bug-fix plans.", piPreferences.planModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: $$event.target.value,
                                                      implementationModel: previous.implementationModel
                                                    };
                                            });
                                      })),
                                renderModelSelect("Plan implementation", "Turns an accepted plan into an applicable patch.", piPreferences.implementationModel, true, (function ($$event) {
                                        setPiPreferences(function (previous) {
                                              return {
                                                      defaultModel: previous.defaultModel,
                                                      inlineReviewModel: previous.inlineReviewModel,
                                                      codeReviewModel: previous.codeReviewModel,
                                                      securityReviewModel: previous.securityReviewModel,
                                                      specReviewModel: previous.specReviewModel,
                                                      suggestionModel: previous.suggestionModel,
                                                      validationModel: previous.validationModel,
                                                      planModel: previous.planModel,
                                                      implementationModel: $$event.target.value
                                                    };
                                            });
                                      }))
                              ],
                              className: settingsGrid
                            }),
                        JsxRuntime.jsx("p", {
                              children: piModelsError !== "" ? "Could not load Pi models: " + piModelsError : (
                                  isThemeLoading ? "Applying themes…" : "Preferences saved locally."
                                ),
                              className: settingsHint(currentColors)
                            })
                      ],
                      className: settingsContent
                    }),
                className: settingsPage(currentColors)
              });
  };
  var idlePiStatus;
  switch (viewMode) {
    case "Review" :
        idlePiStatus = activeReview !== undefined ? (
            activeReview === "CodeReview" ? "Code review · " + PiPreferences.resolve(piPreferences, piPreferences.codeReviewModel) : "Security review · " + PiPreferences.resolve(piPreferences, piPreferences.securityReviewModel)
          ) : "Inline Q&A · " + PiPreferences.resolve(piPreferences, piPreferences.inlineReviewModel);
        break;
    case "Feature" :
        var exit = 0;
        var tmp = match$9[0];
        if (typeof tmp !== "object" || tmp.TAG !== "Applying") {
          exit = 1;
        } else {
          idlePiStatus = "Plan implementation · " + PiPreferences.resolve(piPreferences, piPreferences.implementationModel);
        }
        if (exit === 1) {
          idlePiStatus = "Plan creation · " + PiPreferences.resolve(piPreferences, piPreferences.planModel);
        }
        break;
    default:
      idlePiStatus = "Default · " + (
        piPreferences.defaultModel === "" ? piResolvedDefault : piPreferences.defaultModel
      );
  }
  var displayPiModel = function (model) {
    if (model !== "") {
      return model;
    } else if (piResolvedDefault !== "") {
      return piResolvedDefault;
    } else {
      return "Pi default";
    }
  };
  var piStatus;
  if (activePiRun !== undefined) {
    piStatus = activePiRun.action + " · " + displayPiModel(activePiRun.model);
  } else {
    var parts = idlePiStatus.split(" · ");
    var match$21 = parts[0];
    var match$22 = parts[1];
    piStatus = match$21 !== undefined && match$22 !== undefined ? match$21 + " · " + displayPiModel(match$22) : idlePiStatus;
  }
  if (typeof patchState !== "object") {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: isDark ? "Light Mode" : "Dark Mode",
                                      className: buttonStyle,
                                      type: "button",
                                      onClick: handleThemeToggle
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "⚙",
                                      "aria-label": "Open settings",
                                      "aria-pressed": settingsAriaPressed,
                                      className: iconButton(currentColors),
                                      title: "Settings",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Settings";
                                              });
                                        })
                                    })
                              ],
                              className: headerActions
                            }),
                        className: headerStyle
                      }),
                  viewMode === "Settings" ? renderSettings() : JsxRuntime.jsx("div", {
                          children: "Loading diff...",
                          className: loadingContainer
                        })
                ],
                className: container
              });
  }
  if (patchState.TAG !== "PatchReady") {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: isDark ? "Light Mode" : "Dark Mode",
                                      className: buttonStyle,
                                      type: "button",
                                      onClick: handleThemeToggle
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "⚙",
                                      "aria-label": "Open settings",
                                      "aria-pressed": settingsAriaPressed,
                                      className: iconButton(currentColors),
                                      title: "Settings",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Settings";
                                              });
                                        })
                                    })
                              ],
                              className: headerActions
                            }),
                        className: headerStyle
                      }),
                  viewMode === "Settings" ? renderSettings() : JsxRuntime.jsx("div", {
                          children: JsxRuntime.jsx("div", {
                                children: "Failed to load diff:\n\n" + patchState._0,
                                className: errorMessage
                              }),
                          className: errorContainer(currentColors)
                        })
                ],
                className: container
              });
  }
  var tmp$1;
  switch (viewMode) {
    case "Review" :
        tmp$1 = JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("aside", {
                      children: JsxRuntime.jsx(React$2.FileTree, {
                            model: fileTree.model,
                            header: Caml_option.some(JsxRuntime.jsx("div", {
                                      children: "Changed files",
                                      className: treeHeader(currentColors)
                                    })),
                            style: Caml_option.some(treeStyle(currentColors))
                          }),
                      className: sidebar(currentColors)
                    }),
                JsxRuntime.jsx("main", {
                      children: JsxRuntime.jsx(React$1.Virtualizer, {
                            children: diffChildren,
                            style: Caml_option.some({"height": "100%", "overflow-y": "auto"})
                          }),
                      ref: Caml_option.some(virtualizerWrapperRef),
                      className: main
                    })
              ],
              className: content
            });
        break;
    case "Project" :
        tmp$1 = JsxRuntime.jsx(ProjectView.make, {
              theme: style,
              themeType: isDark ? "dark" : "light",
              uiColors: currentColors
            });
        break;
    case "Commit" :
        tmp$1 = null;
        break;
    case "Feature" :
        tmp$1 = JsxRuntime.jsx(NewFeatureView.make, {
              uiColors: currentColors,
              onApplied: requestPatchReload
            });
        break;
    case "Settings" :
        tmp$1 = renderSettings();
        break;

  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Review",
                                      "aria-selected": viewMode === "Review",
                                      className: tab(currentColors),
                                      role: "tab",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Review";
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Project",
                                      "aria-selected": viewMode === "Project",
                                      className: tab(currentColors),
                                      role: "tab",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Project";
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Commit",
                                      "aria-selected": viewMode === "Commit",
                                      className: tab(currentColors),
                                      role: "tab",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Commit";
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "New Feature",
                                      "aria-selected": viewMode === "Feature",
                                      className: tab(currentColors),
                                      role: "tab",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Feature";
                                              });
                                        })
                                    })
                              ],
                              "aria-label": "Main views",
                              className: tabs(currentColors),
                              role: "tablist"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                viewMode === "Review" ? JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx("button", {
                                                children: isReviewing || isAskingPi ? "AI working…" : "AI ▾",
                                                "aria-haspopup": "menu",
                                                className: askPiButton(currentColors, isReviewing || isAskingPi),
                                                type: "button"
                                              }),
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("button", {
                                                        children: isAskingPi ? "Asking Pi…" : "Ask Pi",
                                                        className: aiMenuItem(currentColors, isAskingPi),
                                                        role: "menuitem",
                                                        disabled: isAskingPi,
                                                        type: "button",
                                                        onClick: handleAskPi
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: isCodeReviewing ? "Reviewing…" : "Code Review",
                                                        className: aiMenuItem(currentColors, isReviewing),
                                                        role: "menuitem",
                                                        title: reviewButtonTitle,
                                                        disabled: isReviewing,
                                                        type: "button",
                                                        onClick: (function ($$event) {
                                                            handleFullReview("CodeReview", $$event);
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: isCheckingVulnerabilities ? "Checking…" : "Vulnerability Check",
                                                        className: aiMenuItem(currentColors, isReviewing),
                                                        role: "menuitem",
                                                        title: reviewButtonTitle,
                                                        disabled: isReviewing,
                                                        type: "button",
                                                        onClick: (function ($$event) {
                                                            handleFullReview("VulnerabilityCheck", $$event);
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: "Check against spec",
                                                        className: aiMenuItem(currentColors, false),
                                                        role: "menuitem",
                                                        type: "button",
                                                        onClick: (function (param) {
                                                            setIsSpecCheckOpen(function (param) {
                                                                  return true;
                                                                });
                                                          })
                                                      })
                                                ],
                                                className: aiMenuPanel(currentColors),
                                                role: "menu"
                                              })
                                        ],
                                        className: aiMenu
                                      }) : null,
                                JsxRuntime.jsx("button", {
                                      children: isDark ? "Light Mode" : "Dark Mode",
                                      className: buttonStyle,
                                      type: "button",
                                      onClick: handleThemeToggle
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "⚙",
                                      "aria-label": "Open settings",
                                      "aria-pressed": settingsAriaPressed,
                                      className: iconButton(currentColors),
                                      title: "Settings",
                                      type: "button",
                                      onClick: (function (param) {
                                          setViewMode(function (param) {
                                                return "Settings";
                                              });
                                        })
                                    })
                              ],
                              className: headerActions
                            })
                      ],
                      className: headerStyle
                    }),
                viewMode !== "Commit" && shouldShowReviewSummary ? JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("span", {
                                children: match$13[0],
                                className: reviewSummaryLabel(currentColors)
                              }),
                          reviewSummaryText
                        ],
                        className: reviewSummaryBar(currentColors)
                      }) : null,
                match$17[0] ? JsxRuntime.jsx(SpecCheckView.make, {
                        uiColors: currentColors,
                        themeType: isDark ? "dark" : "light",
                        onClose: (function () {
                            setIsSpecCheckOpen(function (param) {
                                  return false;
                                });
                          }),
                        onChanged: requestPatchReload
                      }) : null,
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(CommitView.make, {
                            patches: patchState._0,
                            repoRoot: match$15[0],
                            theme: style,
                            themeType: isDark ? "dark" : "light",
                            uiColors: currentColors,
                            onCommitted: requestPatchReload
                          }),
                      className: commitViewHost(viewMode !== "Commit")
                    }),
                tmp$1,
                JsxRuntime.jsx("div", {
                      children: "Pi · " + piStatus,
                      className: statusBar(currentColors)
                    })
              ],
              className: container
            });
}

var styled = Html.styled;

var make = App;

export {
  styled ,
  str ,
  Styles ,
  make ,
}
/* headerActions Not a pure module */
