// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Markdown from "./Markdown.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function copyDict(dict) {
  return (Object.assign({}, dict));
}

function deleteProp(dict, key) {
  ((delete dict[key]));
}

function hexToRgba(hex, alpha) {
  return (((hex, alpha) => {
      const cleaned = hex.startsWith('#') ? hex.slice(1) : hex;
      if (cleaned.length < 6) return hex;
      const r = parseInt(cleaned.slice(0, 2), 16);
      const g = parseInt(cleaned.slice(2, 4), 16);
      const b = parseInt(cleaned.slice(4, 6), 16);
      if (isNaN(r) || isNaN(g) || isNaN(b)) return hex;
      return 'rgba(' + r + ', ' + g + ', ' + b + ', ' + alpha + ')';
    })(hex, alpha));
}

function box(colors) {
  return Html.css([
              "\n    display: flex;\n    gap: 8px;\n    margin-top: 4px;\n    margin-bottom: 4px;\n    padding: 8px;\n    border-radius: 4px;\n    background-color: ",
              ";\n    border: 1px solid ",
              ";\n  "
            ], [
              colors.surfaceBg,
              colors.border
            ]);
}

function textarea(colors) {
  var focusShadow = hexToRgba(colors.focusBorder, 0.1);
  return Html.css([
              "\n      flex: 1;\n      min-height: 80px;\n      max-height: 200px;\n      padding: 6px;\n      border-radius: 4px;\n      border: 1px solid ",
              ";\n      background-color: ",
              ";\n      color: ",
              ";\n      font-family: monospace;\n      font-size: 14px;\n      line-height: 1.5;\n      resize: vertical;\n\n      &::placeholder {\n        color: ",
              ";\n      }\n\n      &:hover {\n        border-color: ",
              ";\n      }\n\n      &:focus {\n        outline: none;\n        border-color: ",
              ";\n        box-shadow: 0 0 0 3px ",
              ";\n      }\n    "
            ], [
              colors.inputBorder,
              colors.inputBg,
              colors.inputFg,
              colors.inputPlaceholder,
              colors.descriptionFg,
              colors.focusBorder,
              focusShadow
            ]);
}

function removeButton(colors) {
  return Html.css([
              "\n    padding: 8px 12px;\n    border-radius: 4px;\n    border: 1px solid transparent;\n    background-color: ",
              ";\n    color: #ffffff;\n    font-size: 13px;\n    font-weight: 500;\n    cursor: pointer;\n    transition: all 0.2s ease;\n    min-width: 80px;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n  "
            ], [colors.dangerBg]);
}

function removeButtonHover(colors) {
  return Html.css([
              "\n    &:hover {\n      background-color: ",
              ";\n      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n      transform: translateY(-1px);\n    }\n    &:active {\n      background-color: ",
              ";\n      transform: translateY(0);\n    }\n  "
            ], [
              colors.dangerHoverBg,
              colors.dangerBg
            ]);
}

function aiReply(colors) {
  return Html.css([
              "\n    margin-top: 8px;\n    padding: 10px 12px;\n    border-radius: 4px;\n    background-color: ",
              ";\n    border-left: 3px solid ",
              ";\n    font-size: 13px;\n    line-height: 1.5;\n    color: ",
              ";\n    word-wrap: break-word;\n    overflow-wrap: break-word;\n\n    & h1, & h2, & h3, & h4, & h5, & h6 {\n      margin: 12px 0 6px 0;\n      font-weight: 600;\n      color: ",
              ";\n    }\n    & h1 { font-size: 18px; }\n    & h2 { font-size: 16px; }\n    & h3 { font-size: 15px; }\n    & h4, & h5, & h6 { font-size: 14px; }\n\n    & p {\n      margin: 4px 0;\n      text-wrap: auto;\n    }\n\n    & ul, & ol {\n      margin: 4px 0;\n      padding-left: 24px;\n      text-wrap: auto;\n    }\n\n    & li {\n      margin: 1px 0;\n    }\n\n    & li > p {\n      margin: 0;\n    }\n\n    & a {\n      color: ",
              ";\n      text-decoration: underline;\n    }\n\n    & strong {\n      font-weight: 600;\n    }\n\n    & em {\n      font-style: italic;\n    }\n\n    & blockquote {\n      margin: 6px 0;\n      padding: 4px 12px;\n      border-left: 2px solid ",
              ";\n      color: ",
              ";\n    }\n\n    & hr {\n      border: none;\n      border-top: 1px solid ",
              ";\n      margin: 12px 0;\n    }\n\n    & code {\n      font-family: monospace;\n      font-size: 12.5px;\n      padding: 1px 4px;\n      border-radius: 3px;\n      background-color: ",
              ";\n      overflow-wrap: anywhere;\n    }\n\n    & pre {\n      margin: 8px 0;\n      padding: 10px 12px;\n      border-radius: 4px;\n      overflow-x: auto;\n      font-size: 12.5px;\n      line-height: 1.5;\n    }\n\n    & pre code {\n      padding: 0;\n      background-color: transparent;\n      font-size: inherit;\n      overflow-wrap: normal;\n    }\n  "
            ], [
              colors.surfaceBg,
              colors.focusBorder,
              colors.fg,
              colors.fg,
              colors.focusBorder,
              colors.border,
              colors.descriptionFg,
              colors.border,
              colors.inputBg
            ]);
}

var aiLoading = Html.css(["\n    margin-top: 8px;\n    padding: 8px 12px;\n    font-size: 13px;\n    color: #9ca3af;\n    font-style: italic;\n  "], []);

function aiError(colors) {
  return Html.css([
              "\n    margin-top: 8px;\n    padding: 8px 12px;\n    border-radius: 4px;\n    background-color: ",
              ";\n    color: #ffffff;\n    font-size: 13px;\n  "
            ], [colors.dangerBg]);
}

var Styles = {
  box: box,
  textarea: textarea,
  removeButton: removeButton,
  removeButtonHover: removeButtonHover,
  aiReply: aiReply,
  aiLoading: aiLoading,
  aiError: aiError
};

function CommentBox(props) {
  var uiColors = props.uiColors;
  var onRemove = props.onRemove;
  var onSave = props.onSave;
  var commentKey = props.commentKey;
  var comment = Belt_Option.getWithDefault(Js_dict.get(props.comments, commentKey), {
        text: "",
        aiReply: "AiIdle"
      });
  var initialText = comment.text;
  var match = React.useState(function () {
        return initialText;
      });
  var setLocalText = match[1];
  var localText = match[0];
  React.useEffect((function () {
          setLocalText(function (param) {
                return initialText;
              });
        }), [initialText]);
  var saveComment = function (_event) {
    onSave(function (prev) {
          var newDict = copyDict(prev);
          var existing = Belt_Option.getWithDefault(Js_dict.get(prev, commentKey), {
                text: "",
                aiReply: "AiIdle"
              });
          newDict[commentKey] = {
            text: localText,
            aiReply: existing.aiReply
          };
          return newDict;
        });
  };
  var removeComment = function (_event) {
    onRemove(function (prev) {
          var newDict = copyDict(prev);
          deleteProp(newDict, commentKey);
          return newDict;
        });
  };
  var partial = comment.aiReply;
  var aiReplyContent;
  if (typeof partial !== "object") {
    aiReplyContent = JsxRuntime.jsx(JsxRuntime.Fragment, {});
  } else {
    switch (partial.TAG) {
      case "AiStreaming" :
          aiReplyContent = JsxRuntime.jsx("div", {
                children: "Pi is thinking..." + partial._0,
                className: aiLoading
              });
          break;
      case "AiDone" :
          aiReplyContent = JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx(Markdown.make, {
                      text: partial._0,
                      themeType: props.themeType
                    }),
                className: aiReply(uiColors)
              });
          break;
      case "AiError" :
          var errMsg = partial._0;
          console.log(errMsg);
          aiReplyContent = JsxRuntime.jsx("div", {
                children: "Pi error: " + errMsg,
                className: aiError(uiColors)
              });
          break;
      
    }
  }
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("textarea", {
                              className: textarea(uiColors),
                              placeholder: "Add a comment for line " + props.lineNumber.toString() + "...",
                              value: localText,
                              onBlur: saveComment,
                              onChange: (function (ev) {
                                  var target = ev.target;
                                  setLocalText(function (param) {
                                        return target.value;
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Remove",
                              className: Html.cx([
                                    removeButton(uiColors),
                                    removeButtonHover(uiColors)
                                  ]),
                              onClick: removeComment
                            })
                      ],
                      className: box(uiColors)
                    }),
                aiReplyContent
              ]
            });
}

var make = CommentBox;

export {
  copyDict ,
  deleteProp ,
  hexToRgba ,
  Styles ,
  make ,
}
/* aiLoading Not a pure module */
