// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Raw from "./Raw.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Diffs from "./Diffs.res.mjs";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/diffs/react";

function str(prim) {
  return prim;
}

function lineKey(fileName, side, lineNumber) {
  return fileName + "|" + side + "|" + lineNumber.toString();
}

var clearFileLineKeys = ((dict, fileName) => {
    const prefix = fileName + "|";
    for (const key of Object.keys(dict)) {
      if (key.startsWith(prefix)) delete dict[key];
    }
  });

function isTruthy(value) {
  if (value !== undefined && value) {
    return true;
  } else {
    return false;
  }
}

var buildSelectedPatch = ((fileDiffs, selectedFiles, excludedLines) => {
    const isFileSelected = (name) => selectedFiles[name] !== false;
    const isExcluded = (fileName, side, lineNumber) =>
      excludedLines[fileName + "|" + side + "|" + lineNumber] === true;
    const newline = String.fromCharCode(10);
    const withoutTrailingNewline = (line) => String(line ?? "").replace(/\n$/, "");
    const countLine = (hunk, prefix) => {
      hunk.oldCount += prefix === "+" ? 0 : 1;
      hunk.newCount += prefix === "-" ? 0 : 1;
      if (prefix === "+" || prefix === "-") hunk.hasChange = true;
    };
    const pushLine = (hunk, prefix, line) => {
      hunk.lines.push(prefix + withoutTrailingNewline(line));
      countLine(hunk, prefix);
    };
    const formatRange = (start, count) => count === 1 ? String(start) : String(start) + "," + String(count);
    const pushHeader = (out, fd) => {
      const name = fd.name || "";
      const prevName = fd.prevName || name;
      out.push("diff --git a/" + prevName + " b/" + name);
      if (fd.type === "new") {
        out.push("new file mode " + (fd.mode || "100644"));
      } else if (fd.type === "deleted") {
        out.push("deleted file mode " + (fd.mode || "100644"));
      }
      if (fd.prevObjectId || fd.newObjectId) {
        const prev = fd.prevObjectId || "0000000";
        const next = fd.newObjectId || "0000000";
        const mode = fd.mode && fd.type === "change" ? " " + fd.mode : "";
        out.push("index " + prev + ".." + next + mode);
      }
      out.push("--- " + (fd.type === "new" ? "/dev/null" : "a/" + prevName));
      out.push("+++ " + (fd.type === "deleted" ? "/dev/null" : "b/" + name));
    };

    const out = [];
    for (const fd of fileDiffs) {
      const fileName = fd.name || "";
      if (!fileName || !isFileSelected(fileName)) continue;

      const fileHunks = [];
      let selectedDelta = 0;
      for (const hunk of fd.hunks || []) {
        const built = {
          oldStart: hunk.deletionStart || 0,
          newStart: (hunk.deletionStart || 0) === 0
            ? (hunk.additionStart || 0) + selectedDelta
            : (hunk.deletionStart || 0) + selectedDelta,
          oldCount: 0,
          newCount: 0,
          lines: [],
          hasChange: false,
          selectedAdds: 0,
          selectedDeletes: 0,
        };
        let deletionLineNumber = hunk.deletionStart || 0;
        let additionLineNumber = hunk.additionStart || 0;
        let deletionIndex = hunk.deletionLineIndex || 0;
        let additionIndex = hunk.additionLineIndex || 0;

        for (const item of hunk.hunkContent || []) {
          if (item.type === "context") {
            const lines = item.lines || 0;
            for (let i = 0; i < lines; i += 1) {
              pushLine(built, " ", (fd.deletionLines || [])[deletionIndex + i]);
            }
            deletionLineNumber += lines;
            additionLineNumber += lines;
            deletionIndex += lines;
            additionIndex += lines;
          } else if (item.type === "change") {
            const deletions = item.deletions || 0;
            const additions = item.additions || 0;
            for (let i = 0; i < deletions; i += 1) {
              const lineNumber = deletionLineNumber + i;
              const line = (fd.deletionLines || [])[deletionIndex + i];
              if (isExcluded(fileName, "deletions", lineNumber)) {
                pushLine(built, " ", line);
              } else {
                pushLine(built, "-", line);
                built.selectedDeletes += 1;
              }
            }
            for (let i = 0; i < additions; i += 1) {
              const lineNumber = additionLineNumber + i;
              if (!isExcluded(fileName, "additions", lineNumber)) {
                pushLine(built, "+", (fd.additionLines || [])[additionIndex + i]);
                built.selectedAdds += 1;
              }
            }
            deletionLineNumber += deletions;
            additionLineNumber += additions;
            deletionIndex += deletions;
            additionIndex += additions;
          }
        }

        selectedDelta += built.selectedAdds - built.selectedDeletes;
        if (built.hasChange) {
          fileHunks.push(built);
        }
      }

      if (fileHunks.length === 0) continue;
      if (out.length > 0) out.push("");
      pushHeader(out, fd);
      for (const hunk of fileHunks) {
        out.push("@@ -" + formatRange(hunk.oldStart, hunk.oldCount) + " +" + formatRange(hunk.newStart, hunk.newCount) + " @@");
        out.push(...hunk.lines);
      }
    }

    return out.length === 0 ? "" : out.join(newline) + newline;
  });

var syncExcludedLineHighlights = ((root, excludedLines) => {
    if (root == null) return () => {};

    const observed = new WeakSet();
    let frame = 0;

    const collectRoots = () => {
      const roots = [root];
      for (const el of root.querySelectorAll("*")) {
        if (el.shadowRoot) roots.push(el.shadowRoot);
      }
      return roots;
    };

    const apply = () => {
      frame = 0;
      const roots = collectRoots();
      for (const currentRoot of roots) {
        for (const el of currentRoot.querySelectorAll("[data-selected-line]")) {
          el.removeAttribute("data-selected-line");
        }
        for (const el of currentRoot.querySelectorAll("[data-baka-excluded-line]")) {
          el.removeAttribute("data-baka-excluded-line");
        }
      }

      for (const line of excludedLines) {
        const type = line.side === "deletions" ? "change-deletion" : "change-addition";
        const lineNumber = String(line.lineNumber);
        const selector = '[data-column-number="' + lineNumber + '"][data-line-type="' + type + '"]';
        for (const currentRoot of roots) {
          for (const el of currentRoot.querySelectorAll(selector)) {
            el.setAttribute("data-baka-excluded-line", "");
          }
        }
      }
    };

    const schedule = () => {
      if (frame !== 0) cancelAnimationFrame(frame);
      frame = requestAnimationFrame(apply);
    };

    const observer = new MutationObserver(() => {
      for (const currentRoot of collectRoots()) {
        if (!observed.has(currentRoot)) {
          observer.observe(currentRoot, {childList: true, subtree: true});
          observed.add(currentRoot);
        }
      }
      schedule();
    });

    for (const currentRoot of collectRoots()) {
      observer.observe(currentRoot, {childList: true, subtree: true});
      observed.add(currentRoot);
    }

    schedule();
    return () => {
      if (frame !== 0) cancelAnimationFrame(frame);
      observer.disconnect();
    };
  });

var syncLineNumberSelection = ((root, fileName, enabled, setExcludedLines) => {
    if (root == null || !enabled) return () => {};

    const observed = new WeakSet();
    const cleanups = [];
    let session = null;

    const collectRoots = () => {
      const roots = [root];
      for (const el of root.querySelectorAll("*")) {
        if (el.shadowRoot) roots.push(el.shadowRoot);
      }
      return roots;
    };

    const sideFromType = (type) => {
      if (type === "change-deletion") return "deletions";
      if (type === "change-addition") return "additions";
    };

    const lineFromElement = (element) => {
      if (!(element instanceof HTMLElement)) return null;
      const numberElement = element.closest("[data-column-number]");
      if (!(numberElement instanceof HTMLElement)) return null;
      const side = sideFromType(numberElement.getAttribute("data-line-type"));
      const lineNumber = Number.parseInt(numberElement.getAttribute("data-column-number") || "", 10);
      if (side == null || !Number.isFinite(lineNumber)) return null;
      const key = fileName + "|" + side + "|" + lineNumber;
      const ownerRoot = numberElement.getRootNode();
      return {element: numberElement, root: ownerRoot, side, lineNumber, key};
    };

    const lineFromEvent = (event) => {
      for (const item of event.composedPath()) {
        const line = lineFromElement(item);
        if (line != null) return line;
      }
      for (const currentRoot of collectRoots()) {
        if (typeof currentRoot.elementFromPoint !== "function") continue;
        const line = lineFromElement(currentRoot.elementFromPoint(event.clientX, event.clientY));
        if (line != null) return line;
      }
      return null;
    };

    const changedNumberElements = (ownerRoot) =>
      Array.from(ownerRoot.querySelectorAll(
        '[data-column-number][data-line-type="change-deletion"],' +
        '[data-column-number][data-line-type="change-addition"]'
      )).filter((element) => lineFromElement(element) != null);

    const linesBetween = (start, end) => {
      if (start == null) return [];
      if (end == null || start.root !== end.root) return [start];
      const elements = changedNumberElements(start.root);
      const startIndex = elements.indexOf(start.element);
      const endIndex = elements.indexOf(end.element);
      if (startIndex < 0 || endIndex < 0) return [start];
      const from = Math.min(startIndex, endIndex);
      const to = Math.max(startIndex, endIndex);
      const seen = new Set();
      const lines = [];
      for (const element of elements.slice(from, to + 1)) {
        const line = lineFromElement(element);
        if (line != null && !seen.has(line.key)) {
          seen.add(line.key);
          lines.push(line);
        }
      }
      return lines;
    };

    const applyLines = (lines) => {
      if (lines.length === 0) return;
      setExcludedLines((prev) => {
        const next = Object.assign({}, prev);
        const allExcluded = lines.every((line) => next[line.key] === true);
        const shouldExclude = !allExcluded;
        for (const line of lines) next[line.key] = shouldExclude;
        return next;
      });
    };

    const onPointerDown = (event) => {
      if (event.button !== 0) return;
      const start = lineFromEvent(event);
      if (start == null) return;
      event.preventDefault();
      event.stopPropagation();
      session = {pointerId: event.pointerId, start, current: start};
      document.addEventListener("pointermove", onPointerMove);
      document.addEventListener("pointerup", onPointerUp);
      document.addEventListener("pointercancel", onPointerCancel);
    };

    const onPointerMove = (event) => {
      if (session == null || event.pointerId !== session.pointerId) return;
      event.preventDefault();
      const current = lineFromEvent(event);
      if (current != null) session.current = current;
    };

    const endSession = () => {
      document.removeEventListener("pointermove", onPointerMove);
      document.removeEventListener("pointerup", onPointerUp);
      document.removeEventListener("pointercancel", onPointerCancel);
      session = null;
    };

    const onPointerUp = (event) => {
      if (session == null || event.pointerId !== session.pointerId) return;
      event.preventDefault();
      applyLines(linesBetween(session.start, session.current));
      endSession();
    };

    const onPointerCancel = (event) => {
      if (session == null || event.pointerId !== session.pointerId) return;
      endSession();
    };

    const attach = () => {
      for (const currentRoot of collectRoots()) {
        if (observed.has(currentRoot)) continue;
        currentRoot.addEventListener("pointerdown", onPointerDown, true);
        cleanups.push(() => currentRoot.removeEventListener("pointerdown", onPointerDown, true));
        observed.add(currentRoot);
      }
    };

    const observer = new MutationObserver(attach);
    observer.observe(root, {childList: true, subtree: true});
    cleanups.push(() => observer.disconnect());
    attach();

    return () => {
      endSession();
      for (const cleanup of cleanups.splice(0)) cleanup();
    };
  });

var treeFont = "\"Ioskeley Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

var excludedLineUnsafeCss = "\n    [data-selected-line] {\n      --diffs-line-bg: var(--diffs-computed-diff-line-bg);\n      color: inherit;\n    }\n\n    [data-selected-line][data-line] span {\n      background-color: transparent !important;\n    }\n\n    [data-baka-excluded-line] {\n      --baka-selection-bg: light-dark(#1f2937, #f3f4f6);\n      --baka-selection-fg: light-dark(#ffffff, #111827);\n      --diffs-computed-selected-line-bg: var(--baka-selection-bg);\n      --diffs-line-bg: var(--baka-selection-bg);\n      color: var(--baka-selection-fg);\n    }\n\n    [data-column-number][data-line-type=\"change-deletion\"],\n    [data-column-number][data-line-type=\"change-addition\"] {\n      cursor: pointer;\n      touch-action: none;\n    }\n  ";

var shell = Html.css([
      "\n    display: flex;\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n    font-family: ",
      ";\n    font-size: 1rem;\n  "
    ], [treeFont]);

function sidebar(colors) {
  return Html.css([
              "\n    width: 320px;\n    min-width: 260px;\n    max-width: 420px;\n    display: flex;\n    flex-direction: column;\n    min-height: 0;\n    border-right: 1px solid ",
              ";\n    background-color: ",
              ";\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

function sidebarHeader(colors) {
  return Html.css([
              "\n    padding: 10px 12px;\n    border-bottom: 1px solid ",
              ";\n    color: ",
              ";\n    font-size: 1rem;\n    font-weight: 600;\n  "
            ], [
              colors.border,
              colors.fg
            ]);
}

var sidebarActions = Html.css(["\n    display: flex;\n    gap: 8px;\n    padding: 8px 12px;\n    border-bottom: 1px solid rgba(127, 127, 127, 0.18);\n  "], []);

function smallButton(colors) {
  return Html.css([
              "\n    padding: 4px 8px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 0.923rem;\n    cursor: pointer;\n    &:hover { background-color: ",
              "; }\n  "
            ], [
              colors.border,
              colors.buttonBg,
              colors.buttonFg,
              colors.buttonHoverBg
            ]);
}

var fileList = Html.css(["\n    overflow: auto;\n    min-height: 0;\n    flex: 1;\n  "], []);

function fileRow(colors, active) {
  return Html.css([
              "\n    display: grid;\n    grid-template-columns: 22px minmax(0, 1fr);\n    align-items: center;\n    gap: 6px;\n    width: 100%;\n    padding: 7px 10px;\n    border-bottom: 1px solid rgba(127, 127, 127, 0.12);\n    background-color: ",
              ";\n    color: ",
              ";\n    text-align: left;\n    cursor: pointer;\n    &:hover { background-color: ",
              "; }\n  "
            ], [
              active ? colors.selectionBg : "transparent",
              colors.fg,
              colors.hoverBg
            ]);
}

var fileName = Html.css(["\n    min-width: 0;\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n    font-size: 1rem;\n  "], []);

function lineCount(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 0.923rem;\n  "
            ], [colors.descriptionFg]);
}

var main = Html.css(["\n    flex: 1;\n    min-width: 0;\n    display: flex;\n    flex-direction: column;\n    overflow: hidden;\n  "], []);

function toolbar(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n    gap: 12px;\n    padding: 8px 12px;\n    border-bottom: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 1rem;\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.fg
            ]);
}

var toolbarActions = Html.css(["\n    display: flex;\n    gap: 8px;\n    align-items: center;\n  "], []);

var activeTitle = Html.css(["\n    min-width: 0;\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n    font-weight: 600;\n  "], []);

var diffPane = Html.css(["\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n  "], []);

function emptyState(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex: 1;\n    padding: 24px;\n    color: ",
              ";\n    font-size: 1rem;\n  "
            ], [colors.descriptionFg]);
}

function commitForm(colors) {
  return Html.css([
              "\n    display: flex;\n    flex-direction: column;\n    gap: 8px;\n    padding: 10px 12px 12px;\n    border-top: 1px solid ",
              ";\n    background-color: ",
              ";\n  "
            ], [
              colors.border,
              colors.inputBg
            ]);
}

function commitField(colors) {
  return Html.css([
              "\n    width: 100%;\n    box-sizing: border-box;\n    border: 1px solid ",
              ";\n    border-radius: 4px;\n    background-color: ",
              ";\n    color: ",
              ";\n    font: inherit;\n    font-size: 1rem;\n    padding: 6px 8px;\n    outline: none;\n    &:focus { border-color: ",
              "; }\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.fg,
              colors.focusBorder
            ]);
}

function commitTextArea(colors) {
  return Html.css([
              "\n    width: 100%;\n    min-height: 64px;\n    resize: vertical;\n    box-sizing: border-box;\n    border: 1px solid ",
              ";\n    border-radius: 4px;\n    background-color: ",
              ";\n    color: ",
              ";\n    font: inherit;\n    font-size: 1rem;\n    padding: 6px 8px;\n    outline: none;\n    &:focus { border-color: ",
              "; }\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.fg,
              colors.focusBorder
            ]);
}

function commitButton(colors, disabled) {
  return Html.css([
              "\n    padding: 6px 10px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 1rem;\n    cursor: ",
              ";\n    opacity: ",
              ";\n    &:hover { background-color: ",
              "; }\n  "
            ], [
              colors.focusBorder,
              colors.buttonBg,
              colors.buttonFg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.55" : "1",
              disabled ? colors.buttonBg : colors.buttonHoverBg
            ]);
}

function commitStatus(colors, isError) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 0.923rem;\n    line-height: 1.4;\n    white-space: pre-wrap;\n    ",
              "\n  "
            ], [
              colors.descriptionFg,
              isError ? "color: " + colors.dangerBg + ";" : ""
            ]);
}

var Styles = {
  treeFont: treeFont,
  excludedLineUnsafeCss: excludedLineUnsafeCss,
  shell: shell,
  sidebar: sidebar,
  sidebarHeader: sidebarHeader,
  sidebarActions: sidebarActions,
  smallButton: smallButton,
  fileList: fileList,
  fileRow: fileRow,
  fileName: fileName,
  lineCount: lineCount,
  main: main,
  toolbar: toolbar,
  toolbarActions: toolbarActions,
  activeTitle: activeTitle,
  diffPane: diffPane,
  emptyState: emptyState,
  commitForm: commitForm,
  commitField: commitField,
  commitTextArea: commitTextArea,
  commitButton: commitButton,
  commitStatus: commitStatus
};

function CommitView(props) {
  var onCommitted = props.onCommitted;
  var uiColors = props.uiColors;
  var themeType = props.themeType;
  var theme = props.theme;
  var patches = props.patches;
  var fileDiffs = React.useMemo((function () {
          return patches.flatMap(function (patch) {
                      return patch.files;
                    });
        }), [patches]);
  var fileNames = React.useMemo((function () {
          return fileDiffs.map(Diffs.fileDiffName);
        }), [fileDiffs]);
  var match = React.useState(function () {
        return {};
      });
  var setSelectedFiles = match[1];
  var selectedFiles = match[0];
  var match$1 = React.useState(function () {
        return {};
      });
  var setExcludedLines = match$1[1];
  var excludedLines = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setActiveFileName = match$2[1];
  var activeFileName = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setCommitMessage = match$3[1];
  var commitMessage = match$3[0];
  var match$4 = React.useState(function () {
        return "";
      });
  var setCommitBody = match$4[1];
  var commitBody = match$4[0];
  var match$5 = React.useState(function () {
        return "";
      });
  var setCommitStatus = match$5[1];
  var commitStatus$1 = match$5[0];
  var match$6 = React.useState(function () {
        return false;
      });
  var setCommitStatusIsError = match$6[1];
  var match$7 = React.useState(function () {
        return false;
      });
  var setIsCommitting = match$7[1];
  var isCommitting = match$7[0];
  var diffPaneRef = React.useRef(null);
  React.useEffect((function () {
          var next = {};
          fileNames.forEach(function (name) {
                next[name] = true;
              });
          setSelectedFiles(function (param) {
                return next;
              });
          setExcludedLines(function (param) {
                return {};
              });
          var first = Belt_Array.get(fileNames, 0);
          if (first !== undefined) {
            setActiveFileName(function (param) {
                  return first;
                });
          } else {
            setActiveFileName(function (param) {
                  return "";
                });
          }
        }), [fileNames]);
  var activeFile = fileDiffs.find(function (fd) {
        return Diffs.fileDiffName(fd) === activeFileName;
      });
  var activeChangedLines = React.useMemo((function () {
          if (activeFile !== undefined) {
            return Diffs.changedLineAnnotations(Caml_option.valFromOption(activeFile));
          } else {
            return [];
          }
        }), [
        activeFileName,
        fileDiffs
      ]);
  var isFileSelected = function (name) {
    var value = Js_dict.get(selectedFiles, name);
    if (value !== undefined) {
      return value;
    } else {
      return true;
    }
  };
  var isLineExcluded = function (key) {
    return isTruthy(Js_dict.get(excludedLines, key));
  };
  var selectedFileCount = Core__Array.reduce(fileNames, 0, (function (count, name) {
          if (isFileSelected(name)) {
            return count + 1 | 0;
          } else {
            return count;
          }
        }));
  var selectedChangedLineCount = Core__Array.reduce(fileDiffs, 0, (function (count, fd) {
          var name = Diffs.fileDiffName(fd);
          if (!isFileSelected(name)) {
            return count;
          }
          var changed = Diffs.changedLineAnnotations(fd);
          var excluded = Core__Array.reduce(changed, 0, (function (excludedCount, annotation) {
                  var key = lineKey(name, annotation.side, annotation.lineNumber);
                  if (isLineExcluded(key)) {
                    return excludedCount + 1 | 0;
                  } else {
                    return excludedCount;
                  }
                }));
          return (count + changed.length | 0) - excluded | 0;
        }));
  var trimmedCommitMessage = commitMessage.trim();
  var canCommit = !isCommitting && trimmedCommitMessage !== "" && selectedChangedLineCount > 0;
  var excludedHighlightLines = activeChangedLines.filter(function (annotation) {
        return isLineExcluded(lineKey(activeFileName, annotation.side, annotation.lineNumber));
      });
  React.useEffect((function () {
          return syncExcludedLineHighlights(diffPaneRef.current, excludedHighlightLines);
        }), [
        activeFileName,
        excludedHighlightLines
      ]);
  var activeFileSelected = isFileSelected(activeFileName);
  React.useEffect((function () {
          return syncLineNumberSelection(diffPaneRef.current, activeFileName, activeFileSelected, setExcludedLines);
        }), [
        activeFileName,
        activeFileSelected
      ]);
  var setAllFiles = function (checked) {
    setSelectedFiles(function (param) {
          var next = {};
          fileNames.forEach(function (name) {
                next[name] = checked;
              });
          return next;
        });
    setExcludedLines(function (param) {
          return {};
        });
  };
  var includeActiveLines = function (_event) {
    if (isFileSelected(activeFileName)) {
      return setExcludedLines(function (prev) {
                  var next = Raw.copyDict(prev);
                  activeChangedLines.forEach(function (annotation) {
                        next[lineKey(activeFileName, annotation.side, annotation.lineNumber)] = false;
                      });
                  return next;
                });
    }
    
  };
  var excludeActiveLines = function (_event) {
    if (isFileSelected(activeFileName)) {
      return setExcludedLines(function (prev) {
                  var next = Raw.copyDict(prev);
                  activeChangedLines.forEach(function (annotation) {
                        next[lineKey(activeFileName, annotation.side, annotation.lineNumber)] = true;
                      });
                  return next;
                });
    }
    
  };
  var handleCommit = function (_event) {
    if (!canCommit) {
      return ;
    }
    var patch = buildSelectedPatch(fileDiffs, selectedFiles, excludedLines);
    if (patch.trim() === "") {
      setCommitStatus(function (param) {
            return "No selected changes to commit.";
          });
      return setCommitStatusIsError(function (param) {
                  return true;
                });
    }
    setIsCommitting(function (param) {
          return true;
        });
    setCommitStatus(function (param) {
          return "Committing selected changes...";
        });
    setCommitStatusIsError(function (param) {
          return false;
        });
    var request = {
      message: trimmedCommitMessage,
      body: commitBody,
      patch: patch
    };
    var onSuccess = function (result) {
      setIsCommitting(function (param) {
            return false;
          });
      setCommitStatus(function (param) {
            return result;
          });
      setCommitStatusIsError(function (param) {
            return false;
          });
      setCommitMessage(function (param) {
            return "";
          });
      setCommitBody(function (param) {
            return "";
          });
      onCommitted();
      return Promise.resolve();
    };
    var onError = function (err) {
      var msg = Raw.errorMessage(err);
      setIsCommitting(function (param) {
            return false;
          });
      setCommitStatus(function (param) {
            return msg;
          });
      setCommitStatusIsError(function (param) {
            return true;
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callCommitSelection(request), onSuccess), onError);
  };
  var optionsObj = React.useMemo((function () {
          return {
                  theme: {
                    light: theme.light,
                    dark: theme.dark
                  },
                  themeType: themeType,
                  diffStyle: "unified",
                  lineHoverHighlight: true,
                  unsafeCSS: Diffs.fontUnsafeCss + excludedLineUnsafeCss
                };
        }), [
        theme,
        themeType
      ]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("aside", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: selectedFileCount.toString() + "/" + fileNames.length.toString() + " files selected",
                              className: sidebarHeader(uiColors)
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "All",
                                      className: smallButton(uiColors),
                                      onClick: (function (param) {
                                          setAllFiles(true);
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "None",
                                      className: smallButton(uiColors),
                                      onClick: (function (param) {
                                          setAllFiles(false);
                                        })
                                    })
                              ],
                              className: sidebarActions
                            }),
                        JsxRuntime.jsx("div", {
                              children: fileDiffs.map(function (fd) {
                                    var name = Diffs.fileDiffName(fd);
                                    var selected = isFileSelected(name);
                                    return JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("input", {
                                                        checked: selected,
                                                        type: "checkbox",
                                                        onChange: (function (ev) {
                                                            var target = ev.target;
                                                            var checked = target.checked;
                                                            setSelectedFiles(function (prev) {
                                                                  var next = Raw.copyDict(prev);
                                                                  next[name] = checked;
                                                                  return next;
                                                                });
                                                            setExcludedLines(function (prev) {
                                                                  var next = Raw.copyDict(prev);
                                                                  clearFileLineKeys(next, name);
                                                                  return next;
                                                                });
                                                          }),
                                                        onClick: (function (ev) {
                                                            ev.stopPropagation();
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("span", {
                                                        children: name,
                                                        className: fileName
                                                      })
                                                ],
                                                className: fileRow(uiColors, name === activeFileName),
                                                onClick: (function (param) {
                                                    setActiveFileName(function (param) {
                                                          return name;
                                                        });
                                                  })
                                              }, name);
                                  }),
                              className: fileList
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("input", {
                                      className: commitField(uiColors),
                                      disabled: isCommitting,
                                      placeholder: "Commit message",
                                      type: "text",
                                      value: commitMessage,
                                      onChange: (function (ev) {
                                          var target = ev.target;
                                          setCommitMessage(function (param) {
                                                return target.value;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("textarea", {
                                      className: commitTextArea(uiColors),
                                      disabled: isCommitting,
                                      placeholder: "Commit comment",
                                      value: commitBody,
                                      onChange: (function (ev) {
                                          var target = ev.target;
                                          setCommitBody(function (param) {
                                                return target.value;
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: isCommitting ? "Committing..." : "Commit selected",
                                      className: commitButton(uiColors, !canCommit),
                                      disabled: !canCommit,
                                      type: "button",
                                      onClick: handleCommit
                                    }),
                                commitStatus$1 === "" ? null : JsxRuntime.jsx("div", {
                                        children: commitStatus$1,
                                        className: commitStatus(uiColors, match$6[0])
                                      })
                              ],
                              className: commitForm(uiColors)
                            })
                      ],
                      className: sidebar(uiColors)
                    }),
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: activeFileName === "" ? "No file selected" : activeFileName,
                                      className: activeTitle
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("span", {
                                              children: selectedChangedLineCount.toString() + " changed lines selected",
                                              className: lineCount(uiColors)
                                            }),
                                        JsxRuntime.jsx("button", {
                                              children: "Include file lines",
                                              className: smallButton(uiColors),
                                              onClick: includeActiveLines
                                            }),
                                        JsxRuntime.jsx("button", {
                                              children: "Exclude file lines",
                                              className: smallButton(uiColors),
                                              onClick: excludeActiveLines
                                            })
                                      ],
                                      className: toolbarActions
                                    })
                              ],
                              className: toolbar(uiColors)
                            }),
                        activeFile !== undefined ? JsxRuntime.jsx(JsxRuntime.Fragment, {
                                children: Caml_option.some(JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsx(React$1.Virtualizer, {
                                                children: JsxRuntime.jsx(React$1.FileDiff, {
                                                      fileDiff: Caml_option.valFromOption(activeFile),
                                                      options: optionsObj
                                                    }),
                                                style: Caml_option.some({"height": "100%", "overflow-y": "auto"})
                                              }),
                                          ref: Caml_option.some(diffPaneRef),
                                          className: diffPane
                                        }, activeFileName))
                              }) : JsxRuntime.jsx("div", {
                                children: "No changed files to commit.",
                                className: emptyState(uiColors)
                              })
                      ],
                      className: main
                    })
              ],
              className: shell
            });
}

var copyBoolDict = Raw.copyDict;

var make = CommitView;

export {
  str ,
  lineKey ,
  copyBoolDict ,
  clearFileLineKeys ,
  isTruthy ,
  buildSelectedPatch ,
  syncExcludedLineHighlights ,
  syncLineNumberSelection ,
  Styles ,
  make ,
}
/* shell Not a pure module */
