// Generated by ReScript, PLEASE EDIT WITH CARE


var fontFamily = "\"Ioskeley Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

var fontUnsafeCss = "\n  :host {\n    --diffs-font-family: " + fontFamily + ";\n    --diffs-header-font-family: " + fontFamily + ";\n  }\n";

function fileDiffName(fd) {
  return (fd.name || "");
}

function fileDiffType(fd) {
  return (fd.type || "");
}

function fileDiffAdditionLines(fd) {
  return (fd.additionLines || []);
}

function fileDiffNewObjectId(fd) {
  return (fd.newObjectId || "");
}

function changedLineAnnotations(fd) {
  return (((fd) => {
    if (!fd || !Array.isArray(fd.hunks)) return [];
    const annotations = [];
    for (const hunk of fd.hunks) {
      const content = Array.isArray(hunk.hunkContent) ? hunk.hunkContent : [];
      let deletionLine = hunk.deletionStart || 0;
      let additionLine = hunk.additionStart || 0;
      for (const item of content) {
        if (item.type === "context") {
          const lines = item.lines || 0;
          deletionLine += lines;
          additionLine += lines;
        } else if (item.type === "change") {
          const deletions = item.deletions || 0;
          const additions = item.additions || 0;
          for (let i = 0; i < deletions; i += 1) {
            annotations.push({side: "deletions", lineNumber: deletionLine + i});
          }
          for (let i = 0; i < additions; i += 1) {
            annotations.push({side: "additions", lineNumber: additionLine + i});
          }
          deletionLine += deletions;
          additionLine += additions;
        }
      }
    }
    return annotations;
  })(fd));
}

function isEmptyFile(fd) {
  return (!!fd && fd.type === "new" && fd.newObjectId === "e69de29" && Array.isArray(fd.additionLines) && fd.additionLines.length === 1 && fd.additionLines[0] === "\n");
}

var FileDiff = {};

var Virtualizer = {};

export {
  fontFamily ,
  fontUnsafeCss ,
  fileDiffName ,
  fileDiffType ,
  fileDiffAdditionLines ,
  fileDiffNewObjectId ,
  changedLineAnnotations ,
  isEmptyFile ,
  FileDiff ,
  Virtualizer ,
}
/* No side effect */
