// Generated by ReScript, PLEASE EDIT WITH CARE


function fileDiffName(fd) {
  return fd.name;
}

var FileDiff = {};

var Virtualizer = {};

export {
  fileDiffName ,
  FileDiff ,
  Virtualizer ,
}
/* No side effect */
