// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Raw from "./Raw.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Diffs from "./Diffs.res.mjs";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as CommentBox from "./CommentBox.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as Diffs$1 from "@pierre/diffs";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/diffs/react";

var listenForEscape = (close => {
    const handler = event => {
      if (event.key === "Escape") close();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  });

function makeKey(fileName, side, lineNumber) {
  return fileName + "|" + side + "|" + lineNumber.toString();
}

function parseKey(key) {
  var parts = key.split("|");
  if (parts.length !== 3) {
    return ;
  }
  var fileName = parts[0];
  var sideStr = parts[1];
  var lineStr = parts[2];
  var lineNumber = Belt_Int.fromString(lineStr);
  if (lineNumber !== undefined) {
    return [
            fileName,
            sideStr,
            lineNumber
          ];
  }
  
}

var backdrop = Html.css(["\n    position: fixed;\n    inset: 0;\n    background-color: rgba(0, 0, 0, 0.5);\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    z-index: 1000;\n  "], []);

function content(colors) {
  return Html.css([
              "\n    background-color: ",
              ";\n    color: ",
              ";\n    border: 1px solid ",
              ";\n    border-radius: 8px;\n    width: 90vw;\n    max-width: 1200px;\n    height: 90vh;\n    display: flex;\n    flex-direction: column;\n    overflow: hidden;\n    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);\n  "
            ], [
              colors.bg,
              colors.fg,
              colors.border
            ]);
}

function embedded(colors) {
  return Html.css([
              "\n    height: 100%;\n    display: flex;\n    flex-direction: column;\n    overflow: hidden;\n    color: ",
              ";\n  "
            ], [colors.fg]);
}

function header(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n    padding: 12px 16px;\n    border-bottom: 1px solid ",
              ";\n    background-color: ",
              ";\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

var headerTitle = Html.css(["\n    margin: 0;\n    font-size: 1.077rem;\n    font-weight: 600;\n    font-family: \"Ioskeley Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;\n  "], []);

var headerActions = Html.css(["\n    display: flex;\n    align-items: center;\n    gap: 8px;\n  "], []);

function askButton(colors) {
  return Html.css([
              "\n    padding: 6px 12px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: #ffffff;\n    font-size: 1rem;\n    font-weight: 500;\n    cursor: pointer;\n    transition: opacity 0.2s ease;\n    &:hover { opacity: 0.85; }\n    &:disabled { opacity: 0.5; cursor: not-allowed; }\n  "
            ], [
              colors.focusBorder,
              colors.focusBorder
            ]);
}

function closeButton(colors) {
  return Html.css([
              "\n    padding: 4px 10px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: transparent;\n    color: ",
              ";\n    font-size: 1.231rem;\n    line-height: 1;\n    cursor: pointer;\n    &:hover { background-color: ",
              "; }\n  "
            ], [
              colors.border,
              colors.fg,
              colors.hoverBg
            ]);
}

var body = Html.css(["\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n    background-color: #ffffff;\n  "], []);

var bodyDark = Html.css(["\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n    background-color: #0d1117;\n  "], []);

function emptyFile(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    height: 100%;\n    color: ",
              ";\n    font-size: 1rem;\n  "
            ], [colors.descriptionFg]);
}

var embeddedBody = Html.css(["\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n    background-color: transparent;\n  "], []);

function status(colors) {
  return Html.css([
              "\n    padding: 24px;\n    color: ",
              ";\n    font-size: 1rem;\n    text-align: center;\n  "
            ], [colors.descriptionFg]);
}

function error(colors) {
  return Html.css([
              "\n    padding: 12px 16px;\n    margin: 12px;\n    border-radius: 4px;\n    background-color: ",
              ";\n    color: #ffffff;\n    font-size: 1rem;\n  "
            ], [colors.dangerBg]);
}

var Styles = {
  backdrop: backdrop,
  content: content,
  embedded: embedded,
  header: header,
  headerTitle: headerTitle,
  headerActions: headerActions,
  askButton: askButton,
  closeButton: closeButton,
  body: body,
  bodyDark: bodyDark,
  emptyFile: emptyFile,
  embeddedBody: embeddedBody,
  status: status,
  error: error
};

function FileViewer(props) {
  var __embedded = props.embedded;
  var onClose = props.onClose;
  var uiColors = props.uiColors;
  var themeType = props.themeType;
  var theme = props.theme;
  var fileName = props.fileName;
  var embedded$1 = __embedded !== undefined ? __embedded : false;
  var initialComments = {};
  var match = React.useState(function () {
        return initialComments;
      });
  var setComments = match[1];
  var comments = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setPatch = match$1[1];
  var patch = match$1[0];
  var match$2 = React.useState(function () {
        
      });
  var setError = match$2[1];
  var error$1 = match$2[0];
  var match$3 = React.useState(function () {
        return false;
      });
  var setIsAskingPi = match$3[1];
  var isAskingPi = match$3[0];
  React.useEffect((function () {
          Js_promise2.$$catch(Js_promise2.then(Ipc.callGetFilePatch(fileName), (function (p) {
                      setPatch(function (param) {
                            return p;
                          });
                      return Promise.resolve();
                    })), (function (e) {
                  setError(function (param) {
                        return String(e);
                      });
                  return Promise.resolve();
                }));
        }), []);
  React.useEffect((function () {
          if (onClose !== undefined) {
            return listenForEscape(onClose);
          }
          
        }), []);
  var fileDiff = React.useMemo((function () {
          if (patch === undefined) {
            return null;
          }
          var parsed = Diffs$1.parsePatchFiles(patch);
          var first = Belt_Array.get(parsed, 0);
          if (first === undefined) {
            return null;
          }
          var fd = Belt_Array.get(first.files, 0);
          if (fd !== undefined) {
            return Caml_option.valFromOption(fd);
          } else {
            return null;
          }
        }), [patch]);
  var annotations = React.useMemo((function () {
          return Core__Array.filterMap(Object.keys(comments), (function (key) {
                        var match = parseKey(key);
                        if (match !== undefined && match[0] === fileName) {
                          return {
                                  side: match[1],
                                  lineNumber: match[2]
                                };
                        }
                        
                      }));
        }), [comments]);
  var toggleComment = React.useCallback((function (props) {
          var lineNumber = props.lineNumber | 0;
          var sideStr = props.annotationSide;
          var key = makeKey(fileName, sideStr, lineNumber);
          setComments(function (prev) {
                var match = Js_dict.get(prev, key);
                if (match !== undefined) {
                  var newDict = Raw.copyDict(prev);
                  Raw.deleteProp(newDict, key);
                  return newDict;
                }
                var newDict$1 = Raw.copyDict(prev);
                newDict$1[key] = {
                  text: "",
                  aiReply: "AiIdle"
                };
                return newDict$1;
              });
        }), []);
  var optionsObj = React.useMemo((function () {
          return {
                  theme: {
                    light: theme.light,
                    dark: theme.dark
                  },
                  themeType: themeType,
                  onLineClick: toggleComment,
                  unsafeCSS: Diffs.fontUnsafeCss
                };
        }), [
        theme,
        themeType,
        toggleComment
      ]);
  var handleAskPi = function (_event) {
    if (isAskingPi) {
      return ;
    }
    var payloadComments = Core__Array.filterMap(Object.keys(comments), (function (key) {
            var c = Js_dict.get(comments, key);
            if (c !== undefined && c.text.trim().length > 0 && c.aiReply === "AiIdle") {
              return {
                      commentKey: key,
                      text: c.text
                    };
            }
            
          }));
    if (payloadComments.length === 0) {
      return setComments(function (prev) {
                  var newDict = Raw.copyDict(prev);
                  Object.keys(newDict).forEach(function (key) {
                        var c = Js_dict.get(newDict, key);
                        if (c !== undefined && c.text.trim().length > 0 && c.aiReply === "AiIdle") {
                          newDict[key] = {
                            text: c.text,
                            aiReply: {
                              TAG: "AiDone",
                              _0: "No new questions — your comments are already reviewed."
                            }
                          };
                          return ;
                        }
                        
                      });
                  return newDict;
                });
    }
    setComments(function (prev) {
          var newDict = Raw.copyDict(prev);
          payloadComments.forEach(function (pc) {
                var c = Js_dict.get(newDict, pc.commentKey);
                if (c !== undefined) {
                  newDict[pc.commentKey] = {
                    text: c.text,
                    aiReply: {
                      TAG: "AiStreaming",
                      _0: ""
                    }
                  };
                  return ;
                }
                
              });
          return newDict;
        });
    setIsAskingPi(function (param) {
          return true;
        });
    var diffText = Belt_Option.getWithDefault(patch, "");
    var onSuccess = function (replies) {
      setComments(function (prev) {
            var newDict = Raw.copyDict(prev);
            replies.forEach(function (reply) {
                  var key = reply.commentKey;
                  var c = Js_dict.get(newDict, key);
                  if (c !== undefined) {
                    newDict[key] = {
                      text: c.text,
                      aiReply: {
                        TAG: "AiDone",
                        _0: reply.reply
                      }
                    };
                    return ;
                  }
                  
                });
            return newDict;
          });
      setIsAskingPi(function (param) {
            return false;
          });
      return Promise.resolve();
    };
    var onError = function (err) {
      var msg = Raw.errorMessage(err);
      setComments(function (prev) {
            var newDict = Raw.copyDict(prev);
            payloadComments.forEach(function (pc) {
                  var c = Js_dict.get(newDict, pc.commentKey);
                  if (c !== undefined) {
                    newDict[pc.commentKey] = {
                      text: c.text,
                      aiReply: {
                        TAG: "AiError",
                        _0: msg
                      }
                    };
                    return ;
                  }
                  
                });
            return newDict;
          });
      setIsAskingPi(function (param) {
            return false;
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callAskPiWithDiff(diffText, payloadComments), onSuccess), onError);
  };
  var stopProp = function (ev) {
    ev.stopPropagation();
  };
  var hasPending = Object.keys(comments).some(function (key) {
        var c = Js_dict.get(comments, key);
        if (c !== undefined && c.text.trim().length > 0) {
          return c.aiReply === "AiIdle";
        } else {
          return false;
        }
      });
  var viewer = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: fileName + (
                          Diffs.isEmptyFile(fileDiff) ? " (empty file)" : ""
                        ),
                        className: headerTitle
                      }),
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("button", {
                                children: isAskingPi ? "Asking Pi..." : "🤖 Ask Pi",
                                className: askButton(uiColors),
                                disabled: isAskingPi || !hasPending,
                                onClick: handleAskPi
                              }),
                          onClose !== undefined ? JsxRuntime.jsx("button", {
                                  children: "✕",
                                  className: closeButton(uiColors),
                                  onClick: (function (param) {
                                      onClose();
                                    })
                                }) : null
                        ],
                        className: headerActions
                      })
                ],
                className: header(uiColors)
              }),
          JsxRuntime.jsx("div", {
                children: patch !== undefined ? (
                    error$1 !== undefined ? JsxRuntime.jsx("div", {
                            children: "Loaded",
                            className: status(uiColors)
                          }) : (
                        Diffs.isEmptyFile(fileDiff) ? JsxRuntime.jsx("div", {
                                children: "(empty file)",
                                className: emptyFile(uiColors)
                              }) : JsxRuntime.jsx(React$1.Virtualizer, {
                                children: JsxRuntime.jsx(React$1.FileDiff, {
                                      fileDiff: fileDiff,
                                      options: optionsObj,
                                      lineAnnotations: annotations,
                                      renderAnnotation: (function (annotation) {
                                          var ckey = makeKey(fileName, annotation.side, annotation.lineNumber);
                                          var match = Js_dict.get(comments, ckey);
                                          if (match !== undefined) {
                                            return JsxRuntime.jsx(CommentBox.make, {
                                                        commentKey: ckey,
                                                        lineNumber: annotation.lineNumber,
                                                        comments: comments,
                                                        onSave: setComments,
                                                        onRemove: setComments,
                                                        uiColors: uiColors,
                                                        themeType: themeType
                                                      });
                                          } else {
                                            return JsxRuntime.jsx("div", {});
                                          }
                                        })
                                    }),
                                style: Caml_option.some({"height": "100%", "overflow-y": "auto"})
                              })
                      )
                  ) : (
                    error$1 !== undefined ? JsxRuntime.jsx("div", {
                            children: "Failed to load file: " + error$1,
                            className: error(uiColors)
                          }) : JsxRuntime.jsx("div", {
                            children: "Loading...",
                            className: status(uiColors)
                          })
                  ),
                className: embedded$1 ? embeddedBody : (
                    themeType === "dark" ? bodyDark : body
                  )
              })
        ],
        className: embedded$1 ? embedded(uiColors) : content(uiColors),
        onClick: stopProp
      });
  if (embedded$1) {
    return viewer;
  } else {
    return JsxRuntime.jsx("div", {
                children: viewer,
                className: backdrop,
                onClick: (function (param) {
                    if (onClose !== undefined) {
                      return onClose();
                    }
                    
                  })
              });
  }
}

var copyDict = Raw.copyDict;

var deleteProp = Raw.deleteProp;

var make = FileViewer;

export {
  copyDict ,
  deleteProp ,
  listenForEscape ,
  makeKey ,
  parseKey ,
  Styles ,
  make ,
}
/* backdrop Not a pure module */
