// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Diffs from "./Diffs.res.mjs";
import * as State from "./State.res.mjs";
import * as Jotai from "jotai";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as CommentBox from "./CommentBox.res.mjs";
import * as FileViewer from "./FileViewer.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/diffs/react";

function copyDict(dict) {
  return (Object.assign({}, dict));
}

function deleteProp(dict, key) {
  ((delete dict[key]));
}

function makeKey(fileName, side, lineNumber) {
  return fileName + "|" + side + "|" + lineNumber.toString();
}

function parseKey(key) {
  var parts = key.split("|");
  if (parts.length !== 3) {
    return ;
  }
  var fileName = parts[0];
  var sideStr = parts[1];
  var lineStr = parts[2];
  var lineNumber = Belt_Int.fromString(lineStr);
  if (lineNumber !== undefined) {
    return [
            fileName,
            sideStr,
            lineNumber
          ];
  }
  
}

function normalizeModelKey(key) {
  var parts = Js_string.split("|", key);
  var match = parts.length;
  if (match !== 3) {
    return key;
  }
  var file = parts[0];
  var side = parts[1];
  var line = parts[2];
  var translatedSide;
  switch (side) {
    case "+" :
        translatedSide = "additions";
        break;
    case "-" :
        translatedSide = "deletions";
        break;
    default:
      translatedSide = side;
  }
  return file + "|" + translatedSide + "|" + line;
}

function fullFileButton(colors) {
  return Html.css([
              "\n    padding: 4px 10px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 12px;\n    cursor: pointer;\n    transition: all 0.15s ease;\n    &:hover {\n      background-color: ",
              ";\n      border-color: ",
              ";\n    }\n  "
            ], [
              colors.border,
              colors.surfaceBg,
              colors.fg,
              colors.hoverBg,
              colors.focusBorder
            ]);
}

var Styles = {
  fullFileButton: fullFileButton
};

function InlineComment(props) {
  var uiColors = props.uiColors;
  var themeType = props.themeType;
  var theme = props.theme;
  var fileDiff = props.fileDiff;
  var match = Jotai.useAtom(State.commentsAtom);
  var setComments = match[1];
  var comments = match[0];
  var fileName = Diffs.fileDiffName(fileDiff);
  var match$1 = React.useState(function () {
        return false;
      });
  var setShowFullFile = match$1[1];
  var toggleComment = React.useCallback((function (props) {
          var lineNumber = (props["lineNumber"]) | 0;
          var sideStr = (props["annotationSide"]);
          var key = makeKey(fileName, sideStr, lineNumber);
          setComments(function (prev) {
                var match = Js_dict.get(prev, key);
                if (match !== undefined) {
                  var newDict = copyDict(prev);
                  deleteProp(newDict, key);
                  return newDict;
                }
                var newDict$1 = copyDict(prev);
                newDict$1[key] = {
                  text: "",
                  aiReply: "AiIdle"
                };
                return newDict$1;
              });
        }), []);
  var annotations = React.useMemo((function () {
          return Core__Array.filterMap(Object.keys(comments), (function (key) {
                        var match = parseKey(key);
                        if (match !== undefined && match[0] === fileName) {
                          return {
                                  side: match[1],
                                  lineNumber: match[2]
                                };
                        }
                        
                      }));
        }), [comments]);
  var optionsObj = React.useMemo((function () {
          return {
                  theme: {
                    light: theme.light,
                    dark: theme.dark
                  },
                  themeType: themeType,
                  onLineClick: toggleComment
                };
        }), [
        theme,
        themeType,
        toggleComment
      ]);
  var fullFileButton$1 = React.useCallback((function (_fd) {
          return JsxRuntime.jsx("button", {
                      children: "View full file",
                      className: fullFileButton(uiColors),
                      onClick: (function (ev) {
                          ev.stopPropagation();
                          setShowFullFile(function (param) {
                                return true;
                              });
                        })
                    });
        }), []);
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(React$1.FileDiff, {
                      fileDiff: fileDiff,
                      options: optionsObj,
                      lineAnnotations: annotations,
                      renderAnnotation: (function (annotation) {
                          var ckey = makeKey(fileName, annotation.side, annotation.lineNumber);
                          var match = Js_dict.get(comments, ckey);
                          if (match !== undefined) {
                            return JsxRuntime.jsx(CommentBox.make, {
                                        commentKey: ckey,
                                        lineNumber: annotation.lineNumber,
                                        comments: comments,
                                        onSave: setComments,
                                        onRemove: setComments,
                                        uiColors: uiColors,
                                        themeType: themeType
                                      });
                          } else {
                            return JsxRuntime.jsx("div", {});
                          }
                        }),
                      renderHeaderPrefix: fullFileButton$1
                    }),
                match$1[0] ? JsxRuntime.jsx(FileViewer.make, {
                        fileName: fileName,
                        theme: theme,
                        themeType: themeType,
                        uiColors: uiColors,
                        onClose: (function () {
                            setShowFullFile(function (param) {
                                  return false;
                                });
                          })
                      }) : null
              ]
            });
}

var make = InlineComment;

export {
  copyDict ,
  deleteProp ,
  makeKey ,
  parseKey ,
  normalizeModelKey ,
  Styles ,
  make ,
}
/* Html Not a pure module */
