// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Raw from "./Raw.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Diffs from "./Diffs.res.mjs";
import * as State from "./State.res.mjs";
import * as Jotai from "jotai";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as CommentBox from "./CommentBox.res.mjs";
import * as FileViewer from "./FileViewer.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/diffs/react";

function makeKey(fileName, side, lineNumber) {
  return fileName + "|" + side + "|" + lineNumber.toString();
}

var cleanModelLine = (line => String(line || "").trim().split("-")[0].replace(/^[+-]/, "").replace(/[^0-9].*$/, ""));

function parseKey(key) {
  var parts = key.split("|");
  if (parts.length !== 3) {
    return ;
  }
  var fileName = parts[0];
  var sideStr = parts[1];
  var lineStr = parts[2];
  var lineNumber = Belt_Int.fromString(lineStr);
  if (lineNumber !== undefined) {
    return [
            fileName,
            sideStr,
            lineNumber
          ];
  }
  
}

function normalizeModelKey(key) {
  var parts = Js_string.split("|", key);
  var match = parts.length;
  if (match !== 3) {
    return key;
  }
  var file = parts[0];
  var side = parts[1].trim();
  var rawLine = parts[2].trim();
  var line = cleanModelLine(rawLine);
  var translatedSide;
  switch (side) {
    case "+" :
    case "addition" :
    case "additions" :
    case "new" :
        translatedSide = "additions";
        break;
    case "-" :
    case "deletion" :
    case "deletions" :
    case "old" :
        translatedSide = "deletions";
        break;
    default:
      translatedSide = rawLine.startsWith("+") ? "additions" : (
          rawLine.startsWith("-") ? "deletions" : side
        );
  }
  return file + "|" + translatedSide + "|" + line;
}

function fullFileButton(colors) {
  return Html.css([
              "\n    padding: 4px 10px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 12px;\n    cursor: pointer;\n    transition: all 0.15s ease;\n    &:hover {\n      background-color: ",
              ";\n      border-color: ",
              ";\n    }\n  "
            ], [
              colors.border,
              colors.surfaceBg,
              colors.fg,
              colors.hoverBg,
              colors.focusBorder
            ]);
}

function emptyFileLabel(colors) {
  return Html.css([
              "\n    margin-left: 8px;\n    color: ",
              ";\n    font-size: 12px;\n  "
            ], [colors.descriptionFg]);
}

function fileReviewList(colors) {
  return Html.css([
              "\n    margin: 0 0 12px 0;\n    padding: 8px 12px 10px 12px;\n    border-top: 1px solid ",
              ";\n    background-color: ",
              ";\n  "
            ], [
              colors.border,
              colors.bg
            ]);
}

function fileReviewHeader(colors) {
  return Html.css([
              "\n    margin: 0 0 6px 0;\n    color: ",
              ";\n    font-family: \"Ioskeley Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;\n    font-size: 12px;\n    font-weight: 600;\n  "
            ], [colors.descriptionFg]);
}

var Styles = {
  fullFileButton: fullFileButton,
  emptyFileLabel: emptyFileLabel,
  fileReviewList: fileReviewList,
  fileReviewHeader: fileReviewHeader
};

function InlineComment(props) {
  var uiColors = props.uiColors;
  var themeType = props.themeType;
  var theme = props.theme;
  var fileDiff = props.fileDiff;
  var match = Jotai.useAtom(State.commentsAtom);
  var setComments = match[1];
  var comments = match[0];
  var fileName = Diffs.fileDiffName(fileDiff);
  var isEmptyFile = Diffs.isEmptyFile(fileDiff);
  var match$1 = React.useState(function () {
        return false;
      });
  var setShowFullFile = match$1[1];
  var toggleComment = React.useCallback((function (props) {
          var lineNumber = props.lineNumber | 0;
          var sideStr = props.annotationSide;
          var key = makeKey(fileName, sideStr, lineNumber);
          setComments(function (prev) {
                var match = Js_dict.get(prev, key);
                if (match !== undefined) {
                  var newDict = Raw.copyDict(prev);
                  Raw.deleteProp(newDict, key);
                  return newDict;
                }
                var newDict$1 = Raw.copyDict(prev);
                newDict$1[key] = {
                  text: "",
                  aiReply: "AiIdle"
                };
                return newDict$1;
              });
        }), []);
  var validAnnotationKeys = React.useMemo((function () {
          var keys = {};
          Diffs.changedLineAnnotations(fileDiff).forEach(function (annotation) {
                keys[makeKey(fileName, annotation.side, annotation.lineNumber)] = true;
              });
          return keys;
        }), [fileDiff]);
  var annotations = React.useMemo((function () {
          return Core__Array.filterMap(Object.keys(comments), (function (key) {
                        var match = parseKey(key);
                        if (match === undefined) {
                          return ;
                        }
                        if (match[0] !== fileName) {
                          return ;
                        }
                        var lineNumber = match[2];
                        var side = match[1];
                        var match$1 = Js_dict.get(validAnnotationKeys, makeKey(fileName, side, lineNumber));
                        if (match$1 !== undefined && match$1) {
                          return {
                                  side: side,
                                  lineNumber: lineNumber
                                };
                        }
                        
                      }));
        }), [
        comments,
        validAnnotationKeys
      ]);
  var fileReviewCommentKeys = React.useMemo((function () {
          return Object.keys(comments).filter(function (key) {
                      var match = parseKey(key);
                      if (match === undefined) {
                        return false;
                      }
                      if (match[0] !== fileName) {
                        return false;
                      }
                      var match$1 = Js_dict.get(validAnnotationKeys, makeKey(fileName, match[1], match[2]));
                      if (match$1 !== undefined && match$1) {
                        return false;
                      } else {
                        return true;
                      }
                    });
        }), [
        comments,
        validAnnotationKeys
      ]);
  var optionsObj = React.useMemo((function () {
          return {
                  theme: {
                    light: theme.light,
                    dark: theme.dark
                  },
                  themeType: themeType,
                  onLineClick: toggleComment,
                  unsafeCSS: Diffs.fontUnsafeCss
                };
        }), [
        theme,
        themeType,
        toggleComment
      ]);
  var fullFileButton$1 = React.useCallback((function (_fd) {
          return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "View full file",
                              className: fullFileButton(uiColors),
                              onClick: (function (ev) {
                                  ev.stopPropagation();
                                  setShowFullFile(function (param) {
                                        return true;
                                      });
                                })
                            }),
                        isEmptyFile ? JsxRuntime.jsx("span", {
                                children: "(empty file)",
                                className: emptyFileLabel(uiColors)
                              }) : null
                      ]
                    });
        }), []);
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(React$1.FileDiff, {
                      fileDiff: fileDiff,
                      options: optionsObj,
                      lineAnnotations: annotations,
                      renderAnnotation: (function (annotation) {
                          var ckey = makeKey(fileName, annotation.side, annotation.lineNumber);
                          var match = Js_dict.get(comments, ckey);
                          if (match !== undefined) {
                            return JsxRuntime.jsx(CommentBox.make, {
                                        commentKey: ckey,
                                        lineNumber: annotation.lineNumber,
                                        comments: comments,
                                        onSave: setComments,
                                        onRemove: setComments,
                                        uiColors: uiColors,
                                        themeType: themeType
                                      });
                          } else {
                            return JsxRuntime.jsx("div", {});
                          }
                        }),
                      renderHeaderPrefix: fullFileButton$1
                    }),
                fileReviewCommentKeys.length > 0 ? JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("div", {
                                children: "File-level review",
                                className: fileReviewHeader(uiColors)
                              }),
                          fileReviewCommentKeys.map(function (key) {
                                var match = parseKey(key);
                                if (match !== undefined) {
                                  return JsxRuntime.jsx(CommentBox.make, {
                                              commentKey: key,
                                              lineNumber: match[2],
                                              comments: comments,
                                              onSave: setComments,
                                              onRemove: setComments,
                                              uiColors: uiColors,
                                              themeType: themeType
                                            }, key);
                                } else {
                                  return null;
                                }
                              })
                        ],
                        className: fileReviewList(uiColors)
                      }) : null,
                match$1[0] ? JsxRuntime.jsx(FileViewer.make, {
                        fileName: fileName,
                        theme: theme,
                        themeType: themeType,
                        uiColors: uiColors,
                        onClose: (function () {
                            setShowFullFile(function (param) {
                                  return false;
                                });
                          })
                      }) : null
              ]
            });
}

var copyDict = Raw.copyDict;

var deleteProp = Raw.deleteProp;

var make = InlineComment;

export {
  copyDict ,
  deleteProp ,
  makeKey ,
  cleanModelLine ,
  parseKey ,
  normalizeModelKey ,
  Styles ,
  make ,
}
/* Html Not a pure module */
