// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as Shiki from "./Shiki.res.mjs";
import * as State from "./State.res.mjs";
import * as Jotai from "jotai";
import * as React from "react";
import * as Markdown from "./Markdown.res.mjs";
import * as ZoomMjs from "./Zoom.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ThemePreferences from "./ThemePreferences.res.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as RegisterLanguagesMjs from "./RegisterLanguages.mjs";

function registerRescript(prim) {
  RegisterLanguagesMjs.registerRescript();
}

function registerOdinExtension(prim) {
  RegisterLanguagesMjs.registerOdinExtension();
}

function installZoomShortcuts(prim) {
  ZoomMjs.installZoomShortcuts();
}

var store = Jotai.createStore();

function start() {
  ZoomMjs.installZoomShortcuts();
  RegisterLanguagesMjs.registerRescript();
  RegisterLanguagesMjs.registerOdinExtension();
  var themeNames = ThemePreferences.load();
  store.set(State.themeAtom, themeNames);
  Shiki.preloadShiki(themeNames.light, themeNames.dark);
  Markdown.preloadMarkdown(themeNames.light, themeNames.dark);
  var domElement = document.querySelector("#root");
  if (domElement == null) {
    return ;
  }
  var root = Client.createRoot(domElement);
  var render = function () {
    root.render(JsxRuntime.jsx(React.StrictMode, {
              children: JsxRuntime.jsx(Jotai.Provider, {
                    children: JsxRuntime.jsx(App.make, {}),
                    store: Caml_option.some(store)
                  })
            }));
  };
  var resolveThemes = function (themes) {
    store.set(State.themeColorsAtom, themes);
    render();
    return Promise.resolve();
  };
  var handleError = function (param) {
    render();
    return Promise.resolve();
  };
  Js_promise2.$$catch(Js_promise2.then(Shiki.loadBothThemes(themeNames.light, themeNames.dark), resolveThemes), handleError);
}

window.addEventListener("DOMContentLoaded", start);

export {
  registerRescript ,
  registerOdinExtension ,
  installZoomShortcuts ,
  store ,
  start ,
}
/* store Not a pure module */
