// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarkdownMjs from "./Markdown.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function preloadMarkdown(prim0, prim1) {
  return MarkdownMjs.preloadMarkdown(prim0, prim1);
}

function renderMarkdown(prim0, prim1) {
  return MarkdownMjs.renderMarkdown(prim0, prim1);
}

function Markdown(props) {
  var html = MarkdownMjs.renderMarkdown(props.text, props.themeType);
  return JsxRuntime.jsx("div", {
              dangerouslySetInnerHTML: {
                __html: html
              }
            });
}

var make = Markdown;

export {
  preloadMarkdown ,
  renderMarkdown ,
  make ,
}
/* ./Markdown.mjs Not a pure module */
