// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Raw from "./Raw.res.mjs";
import * as Html from "./Html.res.mjs";
import * as State from "./State.res.mjs";
import * as Jotai from "jotai";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

function container(colors) {
  return Html.css([
              "\n    display: flex;\n    flex-direction: column;\n    height: 100%;\n    overflow: hidden;\n    background-color: ",
              ";\n  "
            ], [colors.surfaceBg]);
}

var content = Html.css(["\n    display: flex;\n    flex-direction: column;\n    flex: 1;\n    min-height: 0;\n    overflow-y: auto;\n    padding: 24px;\n    gap: 16px;\n  "], []);

function heading(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 1.385rem;\n    font-weight: 600;\n  "
            ], [colors.fg]);
}

function description(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 1rem;\n    line-height: 1.5;\n  "
            ], [colors.descriptionFg]);
}

function textarea(colors) {
  return Html.css([
              "\n    width: 100%;\n    min-height: 200px;\n    box-sizing: border-box;\n    border: 1px solid ",
              ";\n    border-radius: 6px;\n    background-color: ",
              ";\n    color: ",
              ";\n    font: inherit;\n    font-size: 1.077rem;\n    line-height: 1.5;\n    padding: 12px;\n    outline: none;\n    resize: vertical;\n\n    &:focus {\n      border-color: ",
              ";\n    }\n\n    &::placeholder {\n      color: ",
              ";\n    }\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.inputFg,
              colors.focusBorder,
              colors.inputPlaceholder
            ]);
}

var actions = Html.css(["\n    display: flex;\n    gap: 8px;\n    align-items: center;\n  "], []);

function button(colors, disabled) {
  return Html.css([
              "\n    padding: 8px 16px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 1rem;\n    font-weight: 600;\n    cursor: ",
              ";\n    opacity: ",
              ";\n    transition: all 0.2s ease;\n\n    &:hover {\n      background-color: ",
              ";\n      border-color: ",
              ";\n    }\n\n    &:active {\n      transform: translateY(1px);\n    }\n  "
            ], [
              colors.focusBorder,
              colors.buttonBg,
              colors.buttonFg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.55" : "1",
              disabled ? colors.buttonBg : colors.buttonHoverBg,
              disabled ? colors.focusBorder : colors.fg
            ]);
}

function dangerButton(colors, disabled) {
  return Html.css([
              "\n    padding: 8px 16px;\n    border-radius: 4px;\n    border: 1px solid ",
              ";\n    background-color: transparent;\n    color: ",
              ";\n    font-size: 1rem;\n    font-weight: 600;\n    cursor: ",
              ";\n    opacity: ",
              ";\n    transition: all 0.2s ease;\n\n    &:hover {\n      background-color: ",
              ";\n      color: ",
              ";\n    }\n\n    &:active {\n      transform: translateY(1px);\n    }\n  "
            ], [
              colors.dangerBg,
              colors.dangerBg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.55" : "1",
              disabled ? "transparent" : colors.dangerBg,
              disabled ? colors.dangerBg : "#ffffff"
            ]);
}

function planContainer(colors) {
  return Html.css([
              "\n    border: 1px solid ",
              ";\n    border-radius: 6px;\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 1rem;\n    line-height: 1.5;\n    padding: 16px;\n    white-space: pre-wrap;\n    overflow-wrap: break-word;\n    max-height: 400px;\n    overflow-y: auto;\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.fg
            ]);
}

function statusBar(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: center;\n    gap: 8px;\n    padding: 8px 12px;\n    border-top: 1px solid ",
              ";\n    background-color: ",
              ";\n    color: ",
              ";\n    font-size: 0.923rem;\n  "
            ], [
              colors.border,
              colors.inputBg,
              colors.descriptionFg
            ]);
}

var spinner = Html.css(["\n    display: inline-block;\n    animation: spin 1s linear infinite;\n  "], []);

function successBar(colors) {
  return Html.css([
              "\n    padding: 12px;\n    border-radius: 6px;\n    background-color: ",
              "22;\n    border: 1px solid ",
              "44;\n    color: ",
              ";\n    font-size: 1rem;\n    line-height: 1.5;\n    white-space: pre-wrap;\n  "
            ], [
              colors.focusBorder,
              colors.focusBorder,
              colors.fg
            ]);
}

function statusText(colors) {
  return Html.css([
              "\n    color: ",
              ";\n  "
            ], [colors.descriptionFg]);
}

function statusTextError(colors) {
  return Html.css([
              "\n    color: ",
              ";\n  "
            ], [colors.dangerBg]);
}

var Styles = {
  container: container,
  content: content,
  heading: heading,
  description: description,
  textarea: textarea,
  actions: actions,
  button: button,
  dangerButton: dangerButton,
  planContainer: planContainer,
  statusBar: statusBar,
  spinner: spinner,
  successBar: successBar,
  statusText: statusText,
  statusTextError: statusTextError
};

function NewFeatureView(props) {
  var uiColors = props.uiColors;
  var match = Jotai.useAtom(State.featureDescriptionAtom);
  var setFeatureDescription = match[1];
  var featureDescription = match[0];
  var match$1 = Jotai.useAtom(State.featurePlanAtom);
  var setFeaturePlan = match$1[1];
  var featurePlan = match$1[0];
  var isGenerating;
  isGenerating = typeof featurePlan !== "object" && featurePlan === "GeneratingPlan" ? true : false;
  var isApplying;
  isApplying = typeof featurePlan !== "object" && featurePlan === "Applying" ? true : false;
  var planText;
  planText = typeof featurePlan !== "object" || featurePlan.TAG !== "PlanReady" ? "" : featurePlan._0;
  var handleGenerate = function (_event) {
    var trimmed = featureDescription.trim();
    if (trimmed === "") {
      return ;
    }
    setFeaturePlan(function (param) {
          return "GeneratingPlan";
        });
    var onSuccess = function (result) {
      setFeaturePlan(function (param) {
            return {
                    TAG: "PlanReady",
                    _0: result.plan
                  };
          });
      return Promise.resolve();
    };
    var onError = function (err) {
      var msg = Raw.errorMessage(err);
      setFeaturePlan(function (param) {
            return {
                    TAG: "Error",
                    _0: msg
                  };
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callCreateFeaturePlan(trimmed), onSuccess), onError);
  };
  var handleRefine = function (_event) {
    setFeaturePlan(function (param) {
          return "Idle";
        });
    setFeatureDescription(function (param) {
          return "";
        });
  };
  var handleApply = function (_event) {
    var description = featureDescription.trim();
    var plan = planText.trim();
    if (!(description !== "" && plan !== "")) {
      return ;
    }
    setFeaturePlan(function (param) {
          return "Applying";
        });
    var onSuccess = function (result) {
      setFeaturePlan(function (param) {
            return {
                    TAG: "ApplyDone",
                    _0: result
                  };
          });
      return Promise.resolve();
    };
    var onError = function (err) {
      var msg = Raw.errorMessage(err);
      setFeaturePlan(function (param) {
            return {
                    TAG: "Error",
                    _0: msg
                  };
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callApplyFeaturePlan({
                  description: description,
                  plan: plan
                }), onSuccess), onError);
  };
  var canGenerate = !isGenerating && !isApplying && featureDescription.trim() !== "";
  var statusMessage;
  if (typeof featurePlan !== "object") {
    switch (featurePlan) {
      case "Idle" :
          statusMessage = "";
          break;
      case "GeneratingPlan" :
          statusMessage = "Pi is generating a plan... this may take a moment.";
          break;
      case "Applying" :
          statusMessage = "Applying the plan to your codebase...";
          break;
      
    }
  } else {
    switch (featurePlan.TAG) {
      case "PlanReady" :
          statusMessage = "Plan ready. You can refine or apply it.";
          break;
      case "ApplyDone" :
      case "Error" :
          statusMessage = featurePlan._0;
          break;
      
    }
  }
  var statusIsError;
  statusIsError = typeof featurePlan !== "object" || featurePlan.TAG !== "Error" ? false : true;
  var tmp;
  var exit = 0;
  if (typeof featurePlan !== "object" || featurePlan.TAG !== "PlanReady") {
    exit = 1;
  } else {
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx("div", {
                  children: featurePlan._0,
                  className: planContainer(uiColors)
                }),
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("button", {
                          children: "↩ Refine",
                          className: dangerButton(uiColors, false),
                          type: "button",
                          onClick: handleRefine
                        }),
                    JsxRuntime.jsx("button", {
                          children: "✓ Start Applying",
                          className: button(uiColors, false),
                          type: "button",
                          onClick: handleApply
                        })
                  ],
                  className: actions
                })
          ]
        });
  }
  if (exit === 1) {
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx("textarea", {
                  className: textarea(uiColors),
                  disabled: isGenerating || isApplying,
                  placeholder: "Describe the new feature or bug fix in detail...\n\nExample: 'Add a dark mode toggle button to the sidebar'\nOr: 'Fix the issue where undo sometimes crashes when the file has unsaved changes'",
                  value: featureDescription,
                  onChange: (function (ev) {
                      var target = ev.target;
                      setFeatureDescription(function (param) {
                            return target.value;
                          });
                    })
                }),
            JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsx("button", {
                        children: isGenerating ? "Loading... Generating..." : (
                            isApplying ? "Loading... Applying..." : "Create Plan  →"
                          ),
                        className: button(uiColors, !canGenerate),
                        disabled: !canGenerate,
                        type: "button",
                        onClick: handleGenerate
                      }),
                  className: actions
                })
          ]
        });
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "New Feature / Bug Fix",
                              className: heading(uiColors)
                            }),
                        JsxRuntime.jsx("div", {
                              children: "Describe the feature or bug fix you want to implement. Pi will analyze the current codebase and create a plan to guide the implementation.",
                              className: description(uiColors)
                            }),
                        tmp
                      ],
                      className: content
                    }),
                statusMessage === "" ? null : JsxRuntime.jsxs("div", {
                        children: [
                          isGenerating || isApplying ? JsxRuntime.jsx("span", {
                                  children: "*",
                                  className: spinner
                                }) : null,
                          JsxRuntime.jsx("span", {
                                children: statusMessage,
                                className: statusIsError ? statusTextError(uiColors) : statusText(uiColors)
                              })
                        ],
                        className: statusBar(uiColors)
                      })
              ],
              className: container(uiColors)
            });
}

var make = NewFeatureView;

export {
  str ,
  Styles ,
  make ,
}
/* content Not a pure module */
