// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PiPreferencesMjs from "./PiPreferences.mjs";

function load(prim) {
  return PiPreferencesMjs.loadPiPreferences();
}

function save(prim) {
  PiPreferencesMjs.savePiPreferences(prim);
}

function resolve(prim0, prim1) {
  return PiPreferencesMjs.resolvePiModel(prim0, prim1);
}

export {
  load ,
  save ,
  resolve ,
}
/* ./PiPreferences.mjs Not a pure module */
