// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Trees from "./Trees.res.mjs";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as FileViewer from "./FileViewer.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@pierre/trees/react";

var appFont = "\"Ioskeley Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

var content = Html.css(["\n    display: flex;\n    flex: 1;\n    min-height: 0;\n    overflow: hidden;\n  "], []);

function sidebar(colors) {
  return Html.css([
              "\n    width: 280px;\n    min-width: 220px;\n    max-width: 360px;\n    display: flex;\n    flex-direction: column;\n    min-height: 0;\n    border-right: 1px solid ",
              ";\n    background-color: ",
              ";\n    overflow: hidden;\n  "
            ], [
              colors.border,
              colors.surfaceBg
            ]);
}

function treeHeader(colors) {
  return Html.css([
              "\n    padding: 10px 12px;\n    border-bottom: 1px solid ",
              ";\n    color: ",
              ";\n    font-family: ",
              ";\n    font-size: 13px;\n    font-weight: 600;\n  "
            ], [
              colors.border,
              colors.fg,
              appFont
            ]);
}

function treeStyle(colors) {
  return {
          height: "100%",
          "--trees-fg-override": colors.fg,
          "--trees-bg-override": colors.surfaceBg,
          "--trees-border-color-override": colors.border,
          "--trees-selected-bg-override": colors.selectionBg,
          "--trees-selected-fg-override": colors.fg,
          "--trees-font-family-override": appFont
        };
}

function main(colors) {
  return Html.css([
              "\n    flex: 1;\n    min-width: 0;\n    min-height: 0;\n    overflow: hidden;\n    background-color: ",
              ";\n  "
            ], [colors.bg]);
}

function status(colors) {
  return Html.css([
              "\n    height: 100%;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    padding: 24px;\n    color: ",
              ";\n    font-family: ",
              ";\n    font-size: 13px;\n    text-align: center;\n  "
            ], [
              colors.descriptionFg,
              appFont
            ]);
}

function error(colors) {
  return Html.css([
              "\n    color: ",
              ";\n  "
            ], [colors.dangerBg]);
}

var Styles = {
  appFont: appFont,
  content: content,
  sidebar: sidebar,
  treeHeader: treeHeader,
  treeStyle: treeStyle,
  main: main,
  status: status,
  error: error
};

function ProjectView(props) {
  var uiColors = props.uiColors;
  var match = React.useState(function () {
        return "Loading";
      });
  var setState = match[1];
  var state = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setSelectedFile = match$1[1];
  var selectedFile = match$1[0];
  React.useEffect((function () {
          Js_promise2.$$catch(Js_promise2.then(Ipc.callGetProjectFiles(), (function (files) {
                      setState(function (param) {
                            return {
                                    TAG: "Ready",
                                    _0: files
                                  };
                          });
                      setSelectedFile(function (current) {
                            if (current !== undefined && files.includes(current)) {
                              return current;
                            } else {
                              return Belt_Array.get(files, 0);
                            }
                          });
                      return Promise.resolve();
                    })), (function (err) {
                  var message = (String(err).replace(/^Error: /, ''));
                  setState(function (param) {
                        return {
                                TAG: "Failed",
                                _0: message
                              };
                      });
                  return Promise.resolve();
                }));
        }), []);
  var paths;
  paths = typeof state !== "object" ? [] : (
      state.TAG === "Ready" ? state._0 : []
    );
  var fileTree = React$1.useFileTree({
        initialExpansion: "open",
        paths: paths,
        onSelectionChange: (function (selectedPaths) {
            setSelectedFile(function (param) {
                  return Belt_Array.get(selectedPaths, 0);
                });
          })
      });
  React.useEffect((function () {
          Trees.resetPaths(fileTree.model, paths);
        }), [paths]);
  var tmp;
  tmp = typeof state !== "object" ? JsxRuntime.jsx("div", {
          children: "Loading project files...",
          className: status(uiColors)
        }) : (
      state.TAG === "Ready" ? (
          state._0.length !== 0 ? (
              selectedFile !== undefined ? JsxRuntime.jsx(FileViewer.make, {
                      fileName: selectedFile,
                      theme: props.theme,
                      themeType: props.themeType,
                      uiColors: uiColors,
                      embedded: true
                    }, selectedFile) : JsxRuntime.jsx("div", {
                      children: "Select a file to view it.",
                      className: status(uiColors)
                    })
            ) : JsxRuntime.jsx("div", {
                  children: "No project files found.",
                  className: status(uiColors)
                })
        ) : JsxRuntime.jsx("div", {
              children: "Failed to load project files: " + state._0,
              className: status(uiColors) + " " + error(uiColors)
            })
    );
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("aside", {
                      children: JsxRuntime.jsx(React$1.FileTree, {
                            model: fileTree.model,
                            header: Caml_option.some(JsxRuntime.jsx("div", {
                                      children: "Project files",
                                      className: treeHeader(uiColors)
                                    })),
                            style: Caml_option.some(treeStyle(uiColors))
                          }),
                      className: sidebar(uiColors)
                    }),
                JsxRuntime.jsx("main", {
                      children: tmp,
                      className: main(uiColors)
                    })
              ],
              className: content
            });
}

var make = ProjectView;

export {
  Styles ,
  make ,
}
/* content Not a pure module */
