// Generated by ReScript, PLEASE EDIT WITH CARE


var copyDict = (dict => Object.assign({}, dict));

var deleteProp = ((dict, key) => { delete dict[key]; });

var errorMessage = (error => String(error).replace(/^Error: /, ''));

export {
  copyDict ,
  deleteProp ,
  errorMessage ,
}
/* No side effect */
