// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ShikiThemeMjs from "./ShikiTheme.mjs";

function loadThemeColors(prim) {
  return ShikiThemeMjs.loadThemeColors(prim);
}

function loadBothThemes(prim0, prim1) {
  return ShikiThemeMjs.loadBothThemes(prim0, prim1);
}

function preloadShiki(prim0, prim1) {
  return ShikiThemeMjs.preloadShiki(prim0, prim1);
}

export {
  loadThemeColors ,
  loadBothThemes ,
  preloadShiki ,
}
/* ./ShikiTheme.mjs Not a pure module */
