// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ipc from "./Ipc.res.mjs";
import * as Raw from "./Raw.res.mjs";
import * as Html from "./Html.res.mjs";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Markdown from "./Markdown.res.mjs";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var readSelectedFile = (event => new Promise((resolve, reject) => {
    const file = event.target.files && event.target.files[0];
    if (!file) {
      reject(new Error("No file selected"));
      return;
    }
    const reader = new FileReader();
    reader.onload = () => resolve({name: file.name, text: String(reader.result || "")});
    reader.onerror = () => reject(new Error("Could not read the selected file"));
    reader.readAsText(file);
  }));

var overlay = Html.css(["\n    position: fixed;\n    inset: 0;\n    z-index: 1000;\n    display: grid;\n    place-items: center;\n    padding: 24px;\n    background: rgba(0, 0, 0, 0.58);\n  "], []);

function dialog(colors) {
  return Html.css([
              "\n    width: min(820px, 100%);\n    max-height: min(820px, calc(100vh - 48px));\n    display: flex;\n    flex-direction: column;\n    overflow: hidden;\n    border: 1px solid ",
              ";\n    border-radius: 10px;\n    background: ",
              ";\n    color: ",
              ";\n    box-shadow: 0 24px 70px rgba(0, 0, 0, 0.38);\n  "
            ], [
              colors.border,
              colors.surfaceBg,
              colors.fg
            ]);
}

function header(colors) {
  return Html.css([
              "\n    display: flex;\n    align-items: flex-start;\n    justify-content: space-between;\n    gap: 16px;\n    padding: 18px 20px;\n    border-bottom: 1px solid ",
              ";\n  "
            ], [colors.border]);
}

var title = Html.css(["\n    margin: 0 0 5px;\n    font-size: 1.25rem;\n  "], []);

function subtitle(colors) {
  return Html.css([
              "\n    margin: 0;\n    color: ",
              ";\n    line-height: 1.45;\n  "
            ], [colors.descriptionFg]);
}

var body = Html.css(["\n    display: flex;\n    flex-direction: column;\n    gap: 16px;\n    padding: 20px;\n    overflow: auto;\n  "], []);

function textarea(colors) {
  return Html.css([
              "\n    width: 100%;\n    min-height: 260px;\n    box-sizing: border-box;\n    resize: vertical;\n    padding: 12px;\n    border: 1px solid ",
              ";\n    border-radius: 6px;\n    background: ",
              ";\n    color: ",
              ";\n    line-height: 1.5;\n\n    &:focus-visible {\n      outline: 2px solid ",
              ";\n      outline-offset: 1px;\n    }\n  "
            ], [
              colors.inputBorder,
              colors.inputBg,
              colors.inputFg,
              colors.focusBorder
            ]);
}

var row = Html.css(["\n    display: flex;\n    align-items: center;\n    flex-wrap: wrap;\n    gap: 10px;\n  "], []);

function button(colors, primary, disabled) {
  return Html.css([
              "\n    padding: 7px 12px;\n    border: 1px solid ",
              ";\n    border-radius: 5px;\n    background: ",
              ";\n    color: ",
              ";\n    cursor: ",
              ";\n    opacity: ",
              ";\n\n    &:hover {\n      background: ",
              ";\n    }\n  "
            ], [
              primary ? colors.focusBorder : colors.border,
              primary ? colors.selectionBg : colors.buttonBg,
              colors.buttonFg,
              disabled ? "not-allowed" : "pointer",
              disabled ? "0.55" : "1",
              disabled ? (
                  primary ? colors.selectionBg : colors.buttonBg
                ) : colors.buttonHoverBg
            ]);
}

function fileButton(colors) {
  return Html.css([
              "\n    position: relative;\n    overflow: hidden;\n    display: inline-flex;\n    align-items: center;\n    padding: 7px 12px;\n    border: 1px solid ",
              ";\n    border-radius: 5px;\n    background: ",
              ";\n    color: ",
              ";\n    cursor: pointer;\n\n    &:hover {\n      background: ",
              ";\n    }\n\n    & input {\n      position: absolute;\n      inset: 0;\n      opacity: 0;\n      cursor: pointer;\n    }\n  "
            ], [
              colors.border,
              colors.buttonBg,
              colors.buttonFg,
              colors.buttonHoverBg
            ]);
}

function summary(colors) {
  return Html.css([
              "\n    padding: 12px;\n    border: 1px solid ",
              ";\n    border-radius: 6px;\n    background: ",
              ";\n    line-height: 1.5;\n  "
            ], [
              colors.border,
              colors.inputBg
            ]);
}

function finding(colors) {
  return Html.css([
              "\n    display: flex;\n    flex-direction: column;\n    gap: 9px;\n    padding: 14px;\n    border: 1px solid ",
              ";\n    border-radius: 7px;\n    background: ",
              ";\n  "
            ], [
              colors.border,
              colors.bg
            ]);
}

var findingHeader = Html.css(["\n    display: flex;\n    align-items: baseline;\n    justify-content: space-between;\n    gap: 12px;\n  "], []);

function $$location(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 0.9rem;\n  "
            ], [colors.descriptionFg]);
}

function status(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    font-size: 0.92rem;\n  "
            ], [colors.descriptionFg]);
}

function report(colors) {
  return Html.css([
              "\n    padding: 16px;\n    border: 1px solid ",
              ";\n    border-radius: 7px;\n    background: ",
              ";\n  "
            ], [
              colors.focusBorder,
              colors.inputBg
            ]);
}

function error(colors) {
  return Html.css([
              "\n    color: ",
              ";\n    white-space: pre-wrap;\n  "
            ], [colors.dangerBg]);
}

var Styles = {
  overlay: overlay,
  dialog: dialog,
  header: header,
  title: title,
  subtitle: subtitle,
  body: body,
  textarea: textarea,
  row: row,
  button: button,
  fileButton: fileButton,
  summary: summary,
  finding: finding,
  findingHeader: findingHeader,
  $$location: $$location,
  status: status,
  report: report,
  error: error
};

function decisionLabel(decision) {
  if (typeof decision === "object") {
    if (decision.TAG === "Fixed") {
      return "Fixed — " + decision._0;
    } else {
      return "Fix failed — " + decision._0;
    }
  }
  switch (decision) {
    case "Pending" :
        return "Awaiting your decision";
    case "Fixing" :
        return "Applying and validating the fix…";
    case "LeftOut" :
        return "Left out by request";

  }
}

function buildReport(review, decisions) {
  var fixed = {
    contents: 0
  };
  var leftOut = {
    contents: 0
  };
  var unresolved = {
    contents: 0
  };
  var details = review.findings.map(function (finding, index) {
          var state = Core__Option.getOr(Js_dict.get(decisions, index.toString()), "Pending");
          var outcome;
          var exit = 0;
          if (typeof state !== "object") {
            switch (state) {
              case "Pending" :
              case "Fixing" :
                  exit = 1;
                  break;
              case "LeftOut" :
                  leftOut.contents = leftOut.contents + 1 | 0;
                  outcome = "Left out";
                  break;

            }
          } else if (state.TAG === "Fixed") {
            fixed.contents = fixed.contents + 1 | 0;
            outcome = "Fixed";
          } else {
            unresolved.contents = unresolved.contents + 1 | 0;
            outcome = "Not fixed: " + state._0;
          }
          if (exit === 1) {
            unresolved.contents = unresolved.contents + 1 | 0;
            outcome = "Unresolved";
          }
          return "- **" + outcome + "** — " + finding.summary + " (`" + finding.commentKey + "`)";
        }).join("\n");
  return "# Specification check report\n\n" + review.summary + "\n\n- Fixed: " + fixed.contents.toString() + "\n- Left out: " + leftOut.contents.toString() + "\n- Unresolved: " + unresolved.contents.toString() + "\n\n## Outcomes\n\n" + (
          details === "" ? "No differences were found." : details
        );
}

function SpecCheckView(props) {
  var onChanged = props.onChanged;
  var onClose = props.onClose;
  var themeType = props.themeType;
  var uiColors = props.uiColors;
  var match = React.useState(function () {
        return "";
      });
  var setSpec = match[1];
  var spec = match[0];
  var match$1 = React.useState(function () {
        return "Pasted specification";
      });
  var setSourceName = match$1[1];
  var match$2 = React.useState(function () {
        return "Entering";
      });
  var setPhase = match$2[1];
  var phase = match$2[0];
  var match$3 = React.useState(function () {
        return {};
      });
  var setDecisions = match$3[1];
  var decisions = match$3[0];
  var match$4 = React.useState(function () {

      });
  var setReport = match$4[1];
  var report$1 = match$4[0];
  var handleFile = function ($$event) {
    var onSuccess = function (uploaded) {
      setSpec(function (param) {
            return uploaded.text;
          });
      setSourceName(function (param) {
            return uploaded.name;
          });
      setPhase(function (param) {
            return "Entering";
          });
      setReport(function (param) {

          });
      return Promise.resolve();
    };
    var onError = function (error) {
      setPhase(function (param) {
            return {
                    TAG: "Failed",
                    _0: Raw.errorMessage(error)
                  };
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(readSelectedFile($$event), onSuccess), onError);
  };
  var handleCheck = function (param) {
    var trimmed = spec.trim();
    if (trimmed.length <= 0) {
      return ;
    }
    setPhase(function (param) {
          return "Checking";
        });
    setReport(function (param) {

        });
    var onSuccess = function (review) {
      var initial = {};
      review.findings.forEach(function (param, index) {
            initial[index.toString()] = "Pending";
          });
      setDecisions(function (param) {
            return initial;
          });
      setPhase(function (param) {
            return {
                    TAG: "Ready",
                    _0: review
                  };
          });
      return Promise.resolve();
    };
    var onError = function (error) {
      setPhase(function (param) {
            return {
                    TAG: "Failed",
                    _0: Raw.errorMessage(error)
                  };
          });
      return Promise.resolve();
    };
    Js_promise2.$$catch(Js_promise2.then(Ipc.callCheckAgainstSpec(trimmed), onSuccess), onError);
  };
  var tmp;
  var exit = 0;
  if (typeof phase !== "object") {
    if (phase === "Entering") {
      exit = 1;
    } else {
      tmp = JsxRuntime.jsx("div", {
            children: "Pi is comparing the current diff with the specification…",
            className: summary(uiColors)
          });
    }
  } else if (phase.TAG === "Ready") {
    var review = phase._0;
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsx(Markdown.make, {
                        text: review.summary,
                        themeType: themeType
                      }),
                  className: summary(uiColors)
                }),
            review.findings.length === 0 ? JsxRuntime.jsx("div", {
                    children: "No differences from the specification were found.",
                    className: summary(uiColors)
                  }) : review.findings.map(function (finding$1, index) {
                    var state = Core__Option.getOr(Js_dict.get(decisions, index.toString()), "Pending");
                    var busy = state === "Fixing";
                    var tmp;
                    if (finding$1.actionable) {
                      var tmp$1;
                      tmp$1 = typeof state !== "object" ? (
                          state === "Fixing" ? "Fixing…" : "Fix this"
                        ) : (
                          state.TAG === "Fixed" ? "Fix again" : "Fix this"
                        );
                      tmp = JsxRuntime.jsx("button", {
                            children: tmp$1,
                            className: button(uiColors, true, busy),
                            disabled: busy,
                            type: "button",
                            onClick: (function (param) {
                                var key = index.toString();
                                setDecisions(function (previous) {
                                      var next = Raw.copyDict(previous);
                                      next[key] = "Fixing";
                                      return next;
                                    });
                                setReport(function (param) {

                                    });
                                var onSuccess = function (result) {
                                  setDecisions(function (previous) {
                                        var next = Raw.copyDict(previous);
                                        next[key] = {
                                          TAG: "Fixed",
                                          _0: result
                                        };
                                        return next;
                                      });
                                  onChanged();
                                  return Promise.resolve();
                                };
                                var onError = function (error) {
                                  setDecisions(function (previous) {
                                        var next = Raw.copyDict(previous);
                                        next[key] = {
                                          TAG: "FixFailed",
                                          _0: Raw.errorMessage(error)
                                        };
                                        return next;
                                      });
                                  return Promise.resolve();
                                };
                                var request_commentKey = finding$1.commentKey;
                                var request_suggestion = finding$1.suggestion;
                                var request = {
                                  commentKey: request_commentKey,
                                  suggestion: request_suggestion
                                };
                                Js_promise2.$$catch(Js_promise2.then(Ipc.callApplyReviewSuggestion(request), onSuccess), onError);
                              })
                          });
                    } else {
                      tmp = null;
                    }
                    return JsxRuntime.jsxs("article", {
                                children: [
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx("strong", {
                                                children: finding$1.summary
                                              }),
                                          JsxRuntime.jsx("span", {
                                                children: finding$1.commentKey,
                                                className: $$location(uiColors)
                                              })
                                        ],
                                        className: findingHeader
                                      }),
                                  JsxRuntime.jsx(Markdown.make, {
                                        text: finding$1.body,
                                        themeType: themeType
                                      }),
                                  JsxRuntime.jsx("div", {
                                        children: decisionLabel(state),
                                        className: status(uiColors)
                                      }),
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          tmp,
                                          JsxRuntime.jsx("button", {
                                                children: "Leave out",
                                                className: button(uiColors, false, busy),
                                                disabled: busy,
                                                type: "button",
                                                onClick: (function (param) {
                                                    setDecisions(function (previous) {
                                                          var next = Raw.copyDict(previous);
                                                          next[index.toString()] = "LeftOut";
                                                          return next;
                                                        });
                                                    setReport(function (param) {

                                                        });
                                                  })
                                              })
                                        ],
                                        className: row
                                      })
                                ],
                                className: finding(uiColors)
                              }, index.toString());
                  }),
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("button", {
                          children: "Produce report",
                          className: button(uiColors, true, false),
                          type: "button",
                          onClick: (function (param) {
                              setReport(function (param) {
                                    return buildReport(review, decisions);
                                  });
                            })
                        }),
                    JsxRuntime.jsx("button", {
                          children: "Change specification",
                          className: button(uiColors, false, false),
                          type: "button",
                          onClick: (function (param) {
                              setPhase(function (param) {
                                    return "Entering";
                                  });
                            })
                        })
                  ],
                  className: row
                }),
            report$1 !== undefined ? JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx(Markdown.make, {
                          text: report$1,
                          themeType: themeType
                        }),
                    className: report(uiColors)
                  }) : null
          ]
        });
  } else {
    exit = 1;
  }
  if (exit === 1) {
    var tmp$1;
    tmp$1 = typeof phase !== "object" || phase.TAG !== "Failed" ? null : JsxRuntime.jsx("div", {
            children: phase._0,
            className: error(uiColors)
          });
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("label", {
                          children: [
                            "Upload Markdown",
                            JsxRuntime.jsx("input", {
                                  accept: ".md,.markdown,text/markdown,text/plain",
                                  type: "file",
                                  onChange: handleFile
                                })
                          ],
                          className: fileButton(uiColors)
                        }),
                    JsxRuntime.jsx("span", {
                          children: match$1[0],
                          className: status(uiColors)
                        })
                  ],
                  className: row
                }),
            JsxRuntime.jsx("textarea", {
                  className: textarea(uiColors),
                  placeholder: "Paste the specification here…",
                  value: spec,
                  onChange: (function ($$event) {
                      setSpec(function (param) {
                            return $$event.target.value;
                          });
                      setSourceName(function (param) {
                            return "Pasted specification";
                          });
                      setPhase(function (param) {
                            return "Entering";
                          });
                      setReport(function (param) {

                          });
                    })
                }),
            tmp$1,
            JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsx("button", {
                        children: "Check modifications",
                        className: button(uiColors, true, spec.trim().length === 0),
                        disabled: spec.trim().length === 0,
                        type: "button",
                        onClick: handleCheck
                      }),
                  className: row
                })
          ]
        });
  }
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("section", {
                    children: [
                      JsxRuntime.jsxs("header", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("h2", {
                                            children: "Check against specification",
                                            className: title,
                                            id: "spec-check-title"
                                          }),
                                      JsxRuntime.jsx("p", {
                                            children: "Paste Markdown or upload a .md file. Pi will compare the current modifications with the requirements.",
                                            className: subtitle(uiColors)
                                          })
                                    ]
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Close",
                                    className: button(uiColors, false, false),
                                    type: "button",
                                    onClick: (function (param) {
                                        onClose();
                                      })
                                  })
                            ],
                            className: header(uiColors)
                          }),
                      JsxRuntime.jsx("div", {
                            children: tmp,
                            className: body
                          })
                    ],
                    "aria-modal": true,
                    "aria-labelledby": "spec-check-title",
                    className: dialog(uiColors),
                    role: "dialog"
                  }),
              className: overlay,
              role: "presentation"
            });
}

var make = SpecCheckView;

export {
  readSelectedFile ,
  Styles ,
  decisionLabel ,
  buildReport ,
  make ,
}
/* overlay Not a pure module */
