// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jotai from "jotai";

var counter = Jotai.atom(0);

var commentsAtom = Jotai.atom({});

var reviewSuggestionsAtom = Jotai.atom({});

var themeAtom = Jotai.atom({
      light: "rose-pine-dawn",
      dark: "tokyo-night"
    });

var isDarkAtom = Jotai.atom(true);

var themeColorsAtom = Jotai.atom(undefined);

var featurePlanAtom = Jotai.atom("Idle");

var featureDescriptionAtom = Jotai.atom("");

var defaultUiColors = {
  bg: "#1f2937",
  fg: "#f9fafb",
  border: "#374151",
  buttonBg: "#374151",
  buttonFg: "#f9fafb",
  buttonHoverBg: "#4b5563",
  inputBg: "#111827",
  inputFg: "#f9fafb",
  inputBorder: "#4b5563",
  inputPlaceholder: "#6b7280",
  focusBorder: "#60a5fa",
  selectionBg: "#374151",
  hoverBg: "#4b5563",
  activeSelectionBg: "#4b5563",
  descriptionFg: "#9ca3af",
  surfaceBg: "#1f2937",
  surfaceBorder: "#374151",
  badgeBg: "#374151",
  dangerBg: "#ef4444",
  dangerHoverBg: "#dc2626",
  themeType: "dark"
};

var lightDefaultUiColors = {
  bg: "#f9fafb",
  fg: "#1f2937",
  border: "#e5e7eb",
  buttonBg: "#ffffff",
  buttonFg: "#1f2937",
  buttonHoverBg: "#f3f4f6",
  inputBg: "#ffffff",
  inputFg: "#1f2937",
  inputBorder: "#d1d5db",
  inputPlaceholder: "#9ca3af",
  focusBorder: "#3b82f6",
  selectionBg: "#e5e7eb",
  hoverBg: "#f3f4f6",
  activeSelectionBg: "#e5e7eb",
  descriptionFg: "#9ca3af",
  surfaceBg: "#fafafa",
  surfaceBorder: "#e6e9ef",
  badgeBg: "#ccd0da",
  dangerBg: "#d20f39",
  dangerHoverBg: "#ff6b81",
  themeType: "light"
};

export {
  counter ,
  commentsAtom ,
  reviewSuggestionsAtom ,
  themeAtom ,
  isDarkAtom ,
  defaultUiColors ,
  lightDefaultUiColors ,
  themeColorsAtom ,
  featurePlanAtom ,
  featureDescriptionAtom ,
}
/* counter Not a pure module */
