// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";

var foo = Html.css(["\n.hightlighted {\n  border-bottom: 0em;\n}\n"], []);

export {
  foo ,
}
/* foo Not a pure module */
