// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ThemePreferencesMjs from "./ThemePreferences.mjs";

function load(prim) {
  return ThemePreferencesMjs.loadThemePreferences();
}

function save(prim) {
  ThemePreferencesMjs.saveThemePreferences(prim);
}

function getOptions(prim) {
  return ThemePreferencesMjs.getThemeOptions(prim);
}

export {
  load ,
  save ,
  getOptions ,
}
/* ./ThemePreferences.mjs Not a pure module */
