// Generated by ReScript, PLEASE EDIT WITH CARE


function resetPaths(model, paths) {
  (((model, paths) => { model.resetPaths(paths); })(model, paths));
}

export {
  resetPaths ,
}
/* No side effect */
